//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_stats_addition_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STATS_ADDITION_CONF")]
  public partial class STATS_ADDITION_CONF : global::ProtoBuf.IExtensible
  {
    public STATS_ADDITION_CONF() {}
    
    private int _id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.STATS_ADDITION_CONF.InternalType_stat_list> _stat_list = new global::System.Collections.Generic.List<dataconfig.STATS_ADDITION_CONF.InternalType_stat_list>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stat_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.STATS_ADDITION_CONF.InternalType_stat_list> stat_list
    {
      get { return _stat_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_stat_list")]
  public partial class InternalType_stat_list : global::ProtoBuf.IExtensible
  {
    public InternalType_stat_list() {}
    
    private string _stat_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stat_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stat_name
    {
      get { return _stat_name; }
      set { _stat_name = value; }
    }
    private uint _stat_type = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint stat_type
    {
      get { return _stat_type; }
      set { _stat_type = value; }
    }
    private dataconfig.ProtoFScalar _stat_value = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stat_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar stat_value
    {
      get { return _stat_value; }
      set { _stat_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STATS_ADDITION_CONF_ARRAY")]
  public partial class STATS_ADDITION_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public STATS_ADDITION_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.STATS_ADDITION_CONF> _items = new global::System.Collections.Generic.List<dataconfig.STATS_ADDITION_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.STATS_ADDITION_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}