//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_recommend_item_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RECOMMEND_ITEM_CONF")]
  public partial class RECOMMEND_ITEM_CONF : global::ProtoBuf.IExtensible
  {
    public RECOMMEND_ITEM_CONF() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _recommend_item_list1 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"recommend_item_list1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> recommend_item_list1
    {
      get { return _recommend_item_list1; }
    }
  
    private string _description1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"description1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description1
    {
      get { return _description1; }
      set { _description1 = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _recommend_item_list2 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"recommend_item_list2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> recommend_item_list2
    {
      get { return _recommend_item_list2; }
    }
  
    private string _description2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"description2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description2
    {
      get { return _description2; }
      set { _description2 = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _recommend_item_list3 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"recommend_item_list3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> recommend_item_list3
    {
      get { return _recommend_item_list3; }
    }
  
    private string _description3;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"description3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description3
    {
      get { return _description3; }
      set { _description3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RECOMMEND_ITEM_CONF_ARRAY")]
  public partial class RECOMMEND_ITEM_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public RECOMMEND_ITEM_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.RECOMMEND_ITEM_CONF> _items = new global::System.Collections.Generic.List<dataconfig.RECOMMEND_ITEM_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.RECOMMEND_ITEM_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}