//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_arena_mode_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ARENA_MODE_CONF")]
  public partial class ARENA_MODE_CONF : global::ProtoBuf.IExtensible
  {
    public ARENA_MODE_CONF() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _isEnable;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isEnable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint isEnable
    {
      get { return _isEnable; }
      set { _isEnable = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _tag = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tag
    {
      get { return _tag; }
    }
  
    private uint _capacity;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"capacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint capacity
    {
      get { return _capacity; }
      set { _capacity = value; }
    }
    private string _map_scene = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"map_scene", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string map_scene
    {
      get { return _map_scene; }
      set { _map_scene = value; }
    }
    private string _map_data = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"map_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string map_data
    {
      get { return _map_data; }
      set { _map_data = value; }
    }
    private string _minimap_img = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"minimap_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string minimap_img
    {
      get { return _minimap_img; }
      set { _minimap_img = value; }
    }
    private string _loading_img = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"loading_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loading_img
    {
      get { return _loading_img; }
      set { _loading_img = value; }
    }
    private string _blue_camera = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"blue_camera", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string blue_camera
    {
      get { return _blue_camera; }
      set { _blue_camera = value; }
    }
    private string _red_camera = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"red_camera", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string red_camera
    {
      get { return _red_camera; }
      set { _red_camera = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _map_blue_element = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"map_blue_element", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> map_blue_element
    {
      get { return _map_blue_element; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _map_red_element = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(13, Name=@"map_red_element", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> map_red_element
    {
      get { return _map_red_element; }
    }
  
    private string _ui_scene = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ui_scene", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ui_scene
    {
      get { return _ui_scene; }
      set { _ui_scene = value; }
    }
    private string _modeIcon = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"modeIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modeIcon
    {
      get { return _modeIcon; }
      set { _modeIcon = value; }
    }
    private uint _meleeCreepCount = (uint)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"meleeCreepCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint meleeCreepCount
    {
      get { return _meleeCreepCount; }
      set { _meleeCreepCount = value; }
    }
    private uint _remoteCreepCount = (uint)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"remoteCreepCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint remoteCreepCount
    {
      get { return _remoteCreepCount; }
      set { _remoteCreepCount = value; }
    }
    private uint _cannonCreepCount = (uint)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"cannonCreepCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint cannonCreepCount
    {
      get { return _cannonCreepCount; }
      set { _cannonCreepCount = value; }
    }
    private uint _superCreepCount = (uint)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"superCreepCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint superCreepCount
    {
      get { return _superCreepCount; }
      set { _superCreepCount = value; }
    }
    private dataconfig.ProtoFScalar _AssistTimeout = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"AssistTimeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar AssistTimeout
    {
      get { return _AssistTimeout; }
      set { _AssistTimeout = value; }
    }
    private dataconfig.ProtoFScalar _KillTimeout = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"KillTimeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar KillTimeout
    {
      get { return _KillTimeout; }
      set { _KillTimeout = value; }
    }
    private dataconfig.ProtoFScalar _TimeBetweenKillChains = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"TimeBetweenKillChains", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar TimeBetweenKillChains
    {
      get { return _TimeBetweenKillChains; }
      set { _TimeBetweenKillChains = value; }
    }
    private dataconfig.ProtoFScalar _TimeBetweenKillChains2 = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"TimeBetweenKillChains2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar TimeBetweenKillChains2
    {
      get { return _TimeBetweenKillChains2; }
      set { _TimeBetweenKillChains2 = value; }
    }
    private int _MaxKillChain = (int)0;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"MaxKillChain", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int MaxKillChain
    {
      get { return _MaxKillChain; }
      set { _MaxKillChain = value; }
    }
    private int _MaxDeathInARow = (int)0;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"MaxDeathInARow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int MaxDeathInARow
    {
      get { return _MaxDeathInARow; }
      set { _MaxDeathInARow = value; }
    }
    private int _MinusDeathPerAssist = (int)0;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"MinusDeathPerAssist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int MinusDeathPerAssist
    {
      get { return _MinusDeathPerAssist; }
      set { _MinusDeathPerAssist = value; }
    }
    private dataconfig.ProtoFScalar _DamageFactor = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"DamageFactor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar DamageFactor
    {
      get { return _DamageFactor; }
      set { _DamageFactor = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _Speed_Threshold = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(28, Name=@"Speed_Threshold", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> Speed_Threshold
    {
      get { return _Speed_Threshold; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _Speed_Rate = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(29, Name=@"Speed_Rate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> Speed_Rate
    {
      get { return _Speed_Rate; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _Speed_Change_Anim = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(30, Name=@"Speed_Change_Anim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> Speed_Change_Anim
    {
      get { return _Speed_Change_Anim; }
    }
  
    private dataconfig.ProtoFScalar _GoldInitPerSecond = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"GoldInitPerSecond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar GoldInitPerSecond
    {
      get { return _GoldInitPerSecond; }
      set { _GoldInitPerSecond = value; }
    }
    private int _HeroExpBeginTime = (int)0;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"HeroExpBeginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int HeroExpBeginTime
    {
      get { return _HeroExpBeginTime; }
      set { _HeroExpBeginTime = value; }
    }
    private int _HeroMaxLevel = (int)0;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"HeroMaxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int HeroMaxLevel
    {
      get { return _HeroMaxLevel; }
      set { _HeroMaxLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _HeroExpToLevelUp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(34, Name=@"HeroExpToLevelUp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> HeroExpToLevelUp
    {
      get { return _HeroExpToLevelUp; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _HeroExpPerSecond = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(35, Name=@"HeroExpPerSecond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> HeroExpPerSecond
    {
      get { return _HeroExpPerSecond; }
    }
  
    private dataconfig.ProtoFScalar _HeroExpRate = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"HeroExpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar HeroExpRate
    {
      get { return _HeroExpRate; }
      set { _HeroExpRate = value; }
    }
    private dataconfig.ProtoFScalar _OtherExpRate = null;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"OtherExpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar OtherExpRate
    {
      get { return _OtherExpRate; }
      set { _OtherExpRate = value; }
    }
    private dataconfig.ProtoFScalar _LevelExpRate = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"LevelExpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar LevelExpRate
    {
      get { return _LevelExpRate; }
      set { _LevelExpRate = value; }
    }
    private dataconfig.ProtoFScalar _MinLevelExpRate = null;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"MinLevelExpRate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar MinLevelExpRate
    {
      get { return _MinLevelExpRate; }
      set { _MinLevelExpRate = value; }
    }
    private dataconfig.ProtoFScalar _ConstAttackSpeed = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"ConstAttackSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar ConstAttackSpeed
    {
      get { return _ConstAttackSpeed; }
      set { _ConstAttackSpeed = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _KillStreakExtraGoldAward = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(41, Name=@"KillStreakExtraGoldAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> KillStreakExtraGoldAward
    {
      get { return _KillStreakExtraGoldAward; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _DeathStreakAwardRatio = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(42, Name=@"DeathStreakAwardRatio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> DeathStreakAwardRatio
    {
      get { return _DeathStreakAwardRatio; }
    }
  
    private dataconfig.ProtoFScalar _RevealerStayTime = null;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"RevealerStayTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar RevealerStayTime
    {
      get { return _RevealerStayTime; }
      set { _RevealerStayTime = value; }
    }
    private int _BuildingHurtEffectID = (int)0;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"BuildingHurtEffectID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int BuildingHurtEffectID
    {
      get { return _BuildingHurtEffectID; }
      set { _BuildingHurtEffectID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _CreepSpawnRuleIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(45, Name=@"CreepSpawnRuleIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> CreepSpawnRuleIds
    {
      get { return _CreepSpawnRuleIds; }
    }
  
    private int _GoldAllotRule = (int)0;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"GoldAllotRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int GoldAllotRule
    {
      get { return _GoldAllotRule; }
      set { _GoldAllotRule = value; }
    }
    private bool _openDayNight = (bool)false;
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"openDayNight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool openDayNight
    {
      get { return _openDayNight; }
      set { _openDayNight = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _UsedArenaObject = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(48, Name=@"UsedArenaObject", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> UsedArenaObject
    {
      get { return _UsedArenaObject; }
    }
  
    private int _BGMId = (int)0;
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"BGMId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int BGMId
    {
      get { return _BGMId; }
      set { _BGMId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ARENA_MODE_CONF_ARRAY")]
  public partial class ARENA_MODE_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public ARENA_MODE_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ARENA_MODE_CONF> _items = new global::System.Collections.Generic.List<dataconfig.ARENA_MODE_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ARENA_MODE_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}