//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_operating_popup_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OPERATING_POPUP_CONF")]
  public partial class OPERATING_POPUP_CONF : global::ProtoBuf.IExtensible
  {
    public OPERATING_POPUP_CONF() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _isEnable = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isEnable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int isEnable
    {
      get { return _isEnable; }
      set { _isEnable = value; }
    }
    private int _order = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private ulong _time_start = (ulong)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong time_start
    {
      get { return _time_start; }
      set { _time_start = value; }
    }
    private ulong _time_end = (ulong)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time_end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong time_end
    {
      get { return _time_end; }
      set { _time_end = value; }
    }
    private int _popupPrefabType = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"popupPrefabType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int popupPrefabType
    {
      get { return _popupPrefabType; }
      set { _popupPrefabType = value; }
    }
    private string _POPT1_title = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"POPT1_title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string POPT1_title
    {
      get { return _POPT1_title; }
      set { _POPT1_title = value; }
    }
    private string _POPT1_imgPath = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"POPT1_imgPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string POPT1_imgPath
    {
      get { return _POPT1_imgPath; }
      set { _POPT1_imgPath = value; }
    }
    private string _POPT1_goToWindowID = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"POPT1_goToWindowID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string POPT1_goToWindowID
    {
      get { return _POPT1_goToWindowID; }
      set { _POPT1_goToWindowID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OPERATING_POPUP_CONF_ARRAY")]
  public partial class OPERATING_POPUP_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public OPERATING_POPUP_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.OPERATING_POPUP_CONF> _items = new global::System.Collections.Generic.List<dataconfig.OPERATING_POPUP_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.OPERATING_POPUP_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}