//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_announce_tips.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ANNOUNCE_TIPS")]
  public partial class ANNOUNCE_TIPS : global::ProtoBuf.IExtensible
  {
    public ANNOUNCE_TIPS() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _tips_key = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tips_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tips_key
    {
      get { return _tips_key; }
      set { _tips_key = value; }
    }
    private int _tips_type = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tips_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int tips_type
    {
      get { return _tips_type; }
      set { _tips_type = value; }
    }
    private string _prefabPath = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"prefabPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefabPath
    {
      get { return _prefabPath; }
      set { _prefabPath = value; }
    }
    private string _tips_title = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tips_title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tips_title
    {
      get { return _tips_title; }
      set { _tips_title = value; }
    }
    private string _tips_value = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tips_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tips_value
    {
      get { return _tips_value; }
      set { _tips_value = value; }
    }
    private dataconfig.ProtoFScalar _duration = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private dataconfig.ProtoFScalar _delay = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"delay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar delay
    {
      get { return _delay; }
      set { _delay = value; }
    }
    private int _soundID = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"soundID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int soundID
    {
      get { return _soundID; }
      set { _soundID = value; }
    }
    private int _enemy_soundID = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"enemy_soundID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int enemy_soundID
    {
      get { return _enemy_soundID; }
      set { _enemy_soundID = value; }
    }
    private int _addition_soundID = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"addition_soundID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int addition_soundID
    {
      get { return _addition_soundID; }
      set { _addition_soundID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ANNOUNCE_TIPS_ARRAY")]
  public partial class ANNOUNCE_TIPS_ARRAY : global::ProtoBuf.IExtensible
  {
    public ANNOUNCE_TIPS_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ANNOUNCE_TIPS> _items = new global::System.Collections.Generic.List<dataconfig.ANNOUNCE_TIPS>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ANNOUNCE_TIPS> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}