//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_goods_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GOODS_CONF")]
  public partial class GOODS_CONF : global::ProtoBuf.IExtensible
  {
    public GOODS_CONF() {}
    
    private dataconfig.GoodsType _type = dataconfig.GoodsType.GT_NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.GoodsType.GT_NONE)]
    public dataconfig.GoodsType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _displayName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"displayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string displayName
    {
      get { return _displayName; }
      set { _displayName = value; }
    }
    private string _discription = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"discription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string discription
    {
      get { return _discription; }
      set { _discription = value; }
    }
    private string _bigIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bigIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bigIcon
    {
      get { return _bigIcon; }
      set { _bigIcon = value; }
    }
    private string _iconPath = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"iconPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string iconPath
    {
      get { return _iconPath; }
      set { _iconPath = value; }
    }
    private int _textColor = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"textColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int textColor
    {
      get { return _textColor; }
      set { _textColor = value; }
    }
    private dataconfig.ItemRarity _rarity = dataconfig.ItemRarity.IR_COMMON;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rarity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.ItemRarity.IR_COMMON)]
    public dataconfig.ItemRarity rarity
    {
      get { return _rarity; }
      set { _rarity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GOODS_CONF_ARRAY")]
  public partial class GOODS_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public GOODS_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.GOODS_CONF> _items = new global::System.Collections.Generic.List<dataconfig.GOODS_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.GOODS_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}