//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_resource_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RESOURCE_CONF")]
  public partial class RESOURCE_CONF : global::ProtoBuf.IExtensible
  {
    public RESOURCE_CONF() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _resource_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource_name
    {
      get { return _resource_name; }
      set { _resource_name = value; }
    }
    private dataconfig.ProtoFScalar _begin_resource_percent = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"begin_resource_percent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar begin_resource_percent
    {
      get { return _begin_resource_percent; }
      set { _begin_resource_percent = value; }
    }
    private dataconfig.ProtoFScalar _max_resource = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"max_resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar max_resource
    {
      get { return _max_resource; }
      set { _max_resource = value; }
    }
    private dataconfig.ProtoFScalar _resource_regen = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resource_regen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar resource_regen
    {
      get { return _resource_regen; }
      set { _resource_regen = value; }
    }
    private dataconfig.ProtoFScalar _resource_decay = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"resource_decay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar resource_decay
    {
      get { return _resource_decay; }
      set { _resource_decay = value; }
    }
    private uint _respond_to_time = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"respond_to_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint respond_to_time
    {
      get { return _respond_to_time; }
      set { _respond_to_time = value; }
    }
    private uint _respond_to_got_attack = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"respond_to_got_attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint respond_to_got_attack
    {
      get { return _respond_to_got_attack; }
      set { _respond_to_got_attack = value; }
    }
    private uint _respond_to_got_attack_damage = (uint)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"respond_to_got_attack_damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint respond_to_got_attack_damage
    {
      get { return _respond_to_got_attack_damage; }
      set { _respond_to_got_attack_damage = value; }
    }
    private uint _respond_to_take_attack = (uint)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"respond_to_take_attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint respond_to_take_attack
    {
      get { return _respond_to_take_attack; }
      set { _respond_to_take_attack = value; }
    }
    private uint _respond_to_take_attack_damage = (uint)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"respond_to_take_attack_damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint respond_to_take_attack_damage
    {
      get { return _respond_to_take_attack_damage; }
      set { _respond_to_take_attack_damage = value; }
    }
    private uint _respond_to_cast_ability = (uint)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"respond_to_cast_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint respond_to_cast_ability
    {
      get { return _respond_to_cast_ability; }
      set { _respond_to_cast_ability = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RESOURCE_CONF_ARRAY")]
  public partial class RESOURCE_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public RESOURCE_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.RESOURCE_CONF> _items = new global::System.Collections.Generic.List<dataconfig.RESOURCE_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.RESOURCE_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}