//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_promotion_posters.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PROMOTION_POSTERS")]
  public partial class PROMOTION_POSTERS : global::ProtoBuf.IExtensible
  {
    public PROMOTION_POSTERS() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private bool _Enable = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Enable
    {
      get { return _Enable; }
      set { _Enable = value; }
    }
    private string _GoToWindow = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"GoToWindow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GoToWindow
    {
      get { return _GoToWindow; }
      set { _GoToWindow = value; }
    }
    private string _GoToData = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"GoToData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GoToData
    {
      get { return _GoToData; }
      set { _GoToData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PROMOTION_POSTERS_ARRAY")]
  public partial class PROMOTION_POSTERS_ARRAY : global::ProtoBuf.IExtensible
  {
    public PROMOTION_POSTERS_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.PROMOTION_POSTERS> _items = new global::System.Collections.Generic.List<dataconfig.PROMOTION_POSTERS>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.PROMOTION_POSTERS> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}