//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_attack_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ATTACK_CONF")]
  public partial class ATTACK_CONF : global::ProtoBuf.IExtensible
  {
    public ATTACK_CONF() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _damage_type = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"damage_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string damage_type
    {
      get { return _damage_type; }
      set { _damage_type = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _attack_anim_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"attack_anim_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> attack_anim_name
    {
      get { return _attack_anim_name; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _crit_anim_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"crit_anim_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> crit_anim_name
    {
      get { return _crit_anim_name; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _crit_effect_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"crit_effect_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> crit_effect_id
    {
      get { return _crit_effect_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _cast_effect_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cast_effect_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> cast_effect_id
    {
      get { return _cast_effect_id; }
    }
  
    private dataconfig.ProtoFScalar _cast_time = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cast_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar cast_time
    {
      get { return _cast_time; }
      set { _cast_time = value; }
    }
    private uint _damage_num = (uint)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"damage_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint damage_num
    {
      get { return _damage_num; }
      set { _damage_num = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _damage_percent = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(10, Name=@"damage_percent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> damage_percent
    {
      get { return _damage_percent; }
    }
  
    private dataconfig.ProtoFScalar _attack_time = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"attack_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar attack_time
    {
      get { return _attack_time; }
      set { _attack_time = value; }
    }
    private uint _projectile_id = (uint)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"projectile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint projectile_id
    {
      get { return _projectile_id; }
      set { _projectile_id = value; }
    }
    private uint _curve_id = (uint)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"curve_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint curve_id
    {
      get { return _curve_id; }
      set { _curve_id = value; }
    }
    private uint _direction_type = (uint)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"direction_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint direction_type
    {
      get { return _direction_type; }
      set { _direction_type = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _hit_effect_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(15, Name=@"hit_effect_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> hit_effect_id
    {
      get { return _hit_effect_id; }
    }
  
    private dataconfig.ProtoFScalar _aoe_range = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"aoe_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar aoe_range
    {
      get { return _aoe_range; }
      set { _aoe_range = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _crit_hit_effect_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(17, Name=@"crit_hit_effect_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> crit_hit_effect_id
    {
      get { return _crit_hit_effect_id; }
    }
  
    private dataconfig.ProtoFScalar _turn_speed = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"turn_speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar turn_speed
    {
      get { return _turn_speed; }
      set { _turn_speed = value; }
    }
    private uint _turn_immediate = (uint)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"turn_immediate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint turn_immediate
    {
      get { return _turn_immediate; }
      set { _turn_immediate = value; }
    }
    private int _select_type = (int)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"select_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int select_type
    {
      get { return _select_type; }
      set { _select_type = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _weights = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(21, Name=@"weights", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> weights
    {
      get { return _weights; }
    }
  
    private dataconfig.ProtoFScalar _min_attack_speed = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"min_attack_speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar min_attack_speed
    {
      get { return _min_attack_speed; }
      set { _min_attack_speed = value; }
    }
    private dataconfig.ProtoFScalar _max_attack_speed = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"max_attack_speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar max_attack_speed
    {
      get { return _max_attack_speed; }
      set { _max_attack_speed = value; }
    }
    private dataconfig.ProtoFScalar _cost_resource = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"cost_resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar cost_resource
    {
      get { return _cost_resource; }
      set { _cost_resource = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _valid_tags = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(25, Name=@"valid_tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> valid_tags
    {
      get { return _valid_tags; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _ignores = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(26, Name=@"ignores", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> ignores
    {
      get { return _ignores; }
    }
  
    private bool _ignore_owner = (bool)false;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"ignore_owner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool ignore_owner
    {
      get { return _ignore_owner; }
      set { _ignore_owner = value; }
    }
    private dataconfig.ProtoFScalar _after_attack_ani_force_playtime = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"after_attack_ani_force_playtime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar after_attack_ani_force_playtime
    {
      get { return _after_attack_ani_force_playtime; }
      set { _after_attack_ani_force_playtime = value; }
    }
    private bool _is_assistant_long_term = (bool)false;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"is_assistant_long_term", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool is_assistant_long_term
    {
      get { return _is_assistant_long_term; }
      set { _is_assistant_long_term = value; }
    }
    private bool _dont_turn_body = (bool)false;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"dont_turn_body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool dont_turn_body
    {
      get { return _dont_turn_body; }
      set { _dont_turn_body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ATTACK_CONF_ARRAY")]
  public partial class ATTACK_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public ATTACK_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ATTACK_CONF> _items = new global::System.Collections.Generic.List<dataconfig.ATTACK_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ATTACK_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}