//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_projectile_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PROJECTILE_CONF")]
  public partial class PROJECTILE_CONF : global::ProtoBuf.IExtensible
  {
    public PROJECTILE_CONF() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _play_maker_path = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"play_maker_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string play_maker_path
    {
      get { return _play_maker_path; }
      set { _play_maker_path = value; }
    }
    private uint _defaultSkinID = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"defaultSkinID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint defaultSkinID
    {
      get { return _defaultSkinID; }
      set { _defaultSkinID = value; }
    }
    private int _speed = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private dataconfig.ProtoFScalar _accelerate_speed = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accelerate_speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar accelerate_speed
    {
      get { return _accelerate_speed; }
      set { _accelerate_speed = value; }
    }
    private int _max_speed = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"max_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int max_speed
    {
      get { return _max_speed; }
      set { _max_speed = value; }
    }
    private dataconfig.ProtoFScalar _life_time = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"life_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar life_time
    {
      get { return _life_time; }
      set { _life_time = value; }
    }
    private int _max_range = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"max_range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int max_range
    {
      get { return _max_range; }
      set { _max_range = value; }
    }
    private dataconfig.ProtoFScalar _collider_radius = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"collider_radius", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar collider_radius
    {
      get { return _collider_radius; }
      set { _collider_radius = value; }
    }
    private int _max_hit_time = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"max_hit_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int max_hit_time
    {
      get { return _max_hit_time; }
      set { _max_hit_time = value; }
    }
    private int _fixed_fly_height = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fixed_fly_height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int fixed_fly_height
    {
      get { return _fixed_fly_height; }
      set { _fixed_fly_height = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _valid_tags = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(13, Name=@"valid_tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> valid_tags
    {
      get { return _valid_tags; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _effectPlayerIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"effectPlayerIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> effectPlayerIds
    {
      get { return _effectPlayerIds; }
    }
  
    private int _effectLinkIds = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"effectLinkIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int effectLinkIds
    {
      get { return _effectLinkIds; }
      set { _effectLinkIds = value; }
    }
    private string _finish_effect = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"finish_effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string finish_effect
    {
      get { return _finish_effect; }
      set { _finish_effect = value; }
    }
    private string _MinimapProxyPath = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"MinimapProxyPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MinimapProxyPath
    {
      get { return _MinimapProxyPath; }
      set { _MinimapProxyPath = value; }
    }
    private string _minimap_icon = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"minimap_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string minimap_icon
    {
      get { return _minimap_icon; }
      set { _minimap_icon = value; }
    }
    private dataconfig.ProtoFScalar _visible_range = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"visible_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar visible_range
    {
      get { return _visible_range; }
      set { _visible_range = value; }
    }
    private int _ignore_occlusion = (int)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ignore_occlusion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int ignore_occlusion
    {
      get { return _ignore_occlusion; }
      set { _ignore_occlusion = value; }
    }
    private int _ignore_teammate = (int)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"ignore_teammate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int ignore_teammate
    {
      get { return _ignore_teammate; }
      set { _ignore_teammate = value; }
    }
    private dataconfig.ProtoFScalar _expose_revealer_duration = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"expose_revealer_duration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar expose_revealer_duration
    {
      get { return _expose_revealer_duration; }
      set { _expose_revealer_duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PROJECTILE_CONF_ARRAY")]
  public partial class PROJECTILE_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public PROJECTILE_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.PROJECTILE_CONF> _items = new global::System.Collections.Generic.List<dataconfig.PROJECTILE_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.PROJECTILE_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}