//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_ability_input.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ABILITY_INPUT")]
  public partial class ABILITY_INPUT : global::ProtoBuf.IExtensible
  {
    public ABILITY_INPUT() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _input_type = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"input_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int input_type
    {
      get { return _input_type; }
      set { _input_type = value; }
    }
    private int _not_target_is_cast = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"not_target_is_cast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int not_target_is_cast
    {
      get { return _not_target_is_cast; }
      set { _not_target_is_cast = value; }
    }
    private bool _reactive_no_target = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reactive_no_target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool reactive_no_target
    {
      get { return _reactive_no_target; }
      set { _reactive_no_target = value; }
    }
    private int _input_logic = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"input_logic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int input_logic
    {
      get { return _input_logic; }
      set { _input_logic = value; }
    }
    private string _assistant = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"assistant", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string assistant
    {
      get { return _assistant; }
      set { _assistant = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _cast_distances = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cast_distances", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> cast_distances
    {
      get { return _cast_distances; }
    }
  
    private int _only_search_forward = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"only_search_forward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int only_search_forward
    {
      get { return _only_search_forward; }
      set { _only_search_forward = value; }
    }
    private dataconfig.ProtoFScalar _angle = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private dataconfig.ProtoFScalar _width = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar width
    {
      get { return _width; }
      set { _width = value; }
    }
    private dataconfig.ProtoFScalar _direction_height = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"direction_height", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar direction_height
    {
      get { return _direction_height; }
      set { _direction_height = value; }
    }
    private dataconfig.ProtoFScalar _direction_width = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"direction_width", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar direction_width
    {
      get { return _direction_width; }
      set { _direction_width = value; }
    }
    private dataconfig.ProtoFScalar _search_distance = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"search_distance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar search_distance
    {
      get { return _search_distance; }
      set { _search_distance = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _valid_tags = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(14, Name=@"valid_tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> valid_tags
    {
      get { return _valid_tags; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _ignores = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(15, Name=@"ignores", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> ignores
    {
      get { return _ignores; }
    }
  
    private int _ignore_owner = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ignore_owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int ignore_owner
    {
      get { return _ignore_owner; }
      set { _ignore_owner = value; }
    }
    private int _pick_effet_id = (int)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"pick_effet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int pick_effet_id
    {
      get { return _pick_effet_id; }
      set { _pick_effet_id = value; }
    }
    private int _auto_select_normal_effect = (int)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"auto_select_normal_effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_select_normal_effect
    {
      get { return _auto_select_normal_effect; }
      set { _auto_select_normal_effect = value; }
    }
    private int _auto_select_kill_effect = (int)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"auto_select_kill_effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_select_kill_effect
    {
      get { return _auto_select_kill_effect; }
      set { _auto_select_kill_effect = value; }
    }
    private int _select_type = (int)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"select_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int select_type
    {
      get { return _select_type; }
      set { _select_type = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _weights = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(21, Name=@"weights", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> weights
    {
      get { return _weights; }
    }
  
    private int _kill_effet_id = (int)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"kill_effet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int kill_effet_id
    {
      get { return _kill_effet_id; }
      set { _kill_effet_id = value; }
    }
    private int _can_not_kill_effet_id = (int)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"can_not_kill_effet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int can_not_kill_effet_id
    {
      get { return _can_not_kill_effet_id; }
      set { _can_not_kill_effet_id = value; }
    }
    private int _input_type_old = (int)0;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"input_type_old", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int input_type_old
    {
      get { return _input_type_old; }
      set { _input_type_old = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _AiSkill_type = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(25, Name=@"AiSkill_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AiSkill_type
    {
      get { return _AiSkill_type; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _AiRange = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(26, Name=@"AiRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> AiRange
    {
      get { return _AiRange; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ABILITY_INPUT_ARRAY")]
  public partial class ABILITY_INPUT_ARRAY : global::ProtoBuf.IExtensible
  {
    public ABILITY_INPUT_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ABILITY_INPUT> _items = new global::System.Collections.Generic.List<dataconfig.ABILITY_INPUT>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ABILITY_INPUT> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}