//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_item_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ITEM_CONF")]
  public partial class ITEM_CONF : global::ProtoBuf.IExtensible
  {
    public ITEM_CONF() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _not_in_shop = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"not_in_shop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint not_in_shop
    {
      get { return _not_in_shop; }
      set { _not_in_shop = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _maps = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"maps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> maps
    {
      get { return _maps; }
    }
  
    private string _description = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private string _description_recommend = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"description_recommend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description_recommend
    {
      get { return _description_recommend; }
      set { _description_recommend = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _price = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint price
    {
      get { return _price; }
      set { _price = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _type_tab = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"type_tab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type_tab
    {
      get { return _type_tab; }
      set { _type_tab = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _recipe = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"recipe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> recipe
    {
      get { return _recipe; }
    }
  
    private uint _active_ability = (uint)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"active_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint active_ability
    {
      get { return _active_ability; }
      set { _active_ability = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _passive_abilities = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"passive_abilities", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> passive_abilities
    {
      get { return _passive_abilities; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ITEM_CONF.InternalType_stat_list> _stat_list = new global::System.Collections.Generic.List<dataconfig.ITEM_CONF.InternalType_stat_list>();
    [global::ProtoBuf.ProtoMember(14, Name=@"stat_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ITEM_CONF.InternalType_stat_list> stat_list
    {
      get { return _stat_list; }
    }
  
    private uint _buyer_level = (uint)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"buyer_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint buyer_level
    {
      get { return _buyer_level; }
      set { _buyer_level = value; }
    }
    private string _item_tag = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"item_tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string item_tag
    {
      get { return _item_tag; }
      set { _item_tag = value; }
    }
    private uint _stack_size = (uint)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"stack_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint stack_size
    {
      get { return _stack_size; }
      set { _stack_size = value; }
    }
    private uint _max = (uint)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint max
    {
      get { return _max; }
      set { _max = value; }
    }
    private string _cooldown = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"cooldown", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cooldown
    {
      get { return _cooldown; }
      set { _cooldown = value; }
    }
    private uint _is_consume = (uint)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"is_consume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint is_consume
    {
      get { return _is_consume; }
      set { _is_consume = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_stat_list")]
  public partial class InternalType_stat_list : global::ProtoBuf.IExtensible
  {
    public InternalType_stat_list() {}
    
    private string _stat_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stat_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stat_name
    {
      get { return _stat_name; }
      set { _stat_name = value; }
    }
    private uint _stat_type = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint stat_type
    {
      get { return _stat_type; }
      set { _stat_type = value; }
    }
    private dataconfig.ProtoFScalar _stat_value = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stat_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar stat_value
    {
      get { return _stat_value; }
      set { _stat_value = value; }
    }
    private string _stat_tag = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stat_tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stat_tag
    {
      get { return _stat_tag; }
      set { _stat_tag = value; }
    }
    private string _stat_giver = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"stat_giver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stat_giver
    {
      get { return _stat_giver; }
      set { _stat_giver = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ITEM_CONF_ARRAY")]
  public partial class ITEM_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public ITEM_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ITEM_CONF> _items = new global::System.Collections.Generic.List<dataconfig.ITEM_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ITEM_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}