//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_buff.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BUFF")]
  public partial class BUFF : global::ProtoBuf.IExtensible
  {
    public BUFF() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _prefab_path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"prefab_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefab_path
    {
      get { return _prefab_path; }
      set { _prefab_path = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _is_common_buff = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_common_buff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int is_common_buff
    {
      get { return _is_common_buff; }
      set { _is_common_buff = value; }
    }
    private int _type = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _tags = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tags
    {
      get { return _tags; }
    }
  
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _des_params = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"des_params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> des_params
    {
      get { return _des_params; }
    }
  
    private uint _tips_id = (uint)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tips_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint tips_id
    {
      get { return _tips_id; }
      set { _tips_id = value; }
    }
    private string _head_icon = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"head_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string head_icon
    {
      get { return _head_icon; }
      set { _head_icon = value; }
    }
    private string _tips = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"tips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tips
    {
      get { return _tips; }
      set { _tips = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _life_time = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(13, Name=@"life_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> life_time
    {
      get { return _life_time; }
    }
  
    private int _reduce_stack_num = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"reduce_stack_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int reduce_stack_num
    {
      get { return _reduce_stack_num; }
      set { _reduce_stack_num = value; }
    }
    private int _max_stack_num = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"max_stack_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int max_stack_num
    {
      get { return _max_stack_num; }
      set { _max_stack_num = value; }
    }
    private int _clear_on_death = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"clear_on_death", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int clear_on_death
    {
      get { return _clear_on_death; }
      set { _clear_on_death = value; }
    }
    private bool _pop_stack = (bool)false;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"pop_stack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool pop_stack
    {
      get { return _pop_stack; }
      set { _pop_stack = value; }
    }
    private dataconfig.ProtoFScalar _priority = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private string _effectType = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"effectType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effectType
    {
      get { return _effectType; }
      set { _effectType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BUFF_ARRAY")]
  public partial class BUFF_ARRAY : global::ProtoBuf.IExtensible
  {
    public BUFF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.BUFF> _items = new global::System.Collections.Generic.List<dataconfig.BUFF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.BUFF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}