//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_lualist.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LUALIST")]
  public partial class LUALIST : global::ProtoBuf.IExtensible
  {
    public LUALIST() {}
    
    private string _path = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private int _auto_replace_multi_ability = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"auto_replace_multi_ability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_replace_multi_ability
    {
      get { return _auto_replace_multi_ability; }
      set { _auto_replace_multi_ability = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LUALIST_ARRAY")]
  public partial class LUALIST_ARRAY : global::ProtoBuf.IExtensible
  {
    public LUALIST_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.LUALIST> _items = new global::System.Collections.Generic.List<dataconfig.LUALIST>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.LUALIST> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}