//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_ai_elo.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AI_ELO")]
  public partial class AI_ELO : global::ProtoBuf.IExtensible
  {
    public AI_ELO() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _elo_range = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"elo_range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> elo_range
    {
      get { return _elo_range; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiLevel> _ai_level_1 = new global::System.Collections.Generic.List<dataconfig.AiLevel>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ai_level_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiLevel> ai_level_1
    {
      get { return _ai_level_1; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiLevel> _ai_level_2 = new global::System.Collections.Generic.List<dataconfig.AiLevel>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ai_level_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiLevel> ai_level_2
    {
      get { return _ai_level_2; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiLevel> _ai_level_3 = new global::System.Collections.Generic.List<dataconfig.AiLevel>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ai_level_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiLevel> ai_level_3
    {
      get { return _ai_level_3; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiLevel> _ai_level_4 = new global::System.Collections.Generic.List<dataconfig.AiLevel>();
    [global::ProtoBuf.ProtoMember(6, Name=@"ai_level_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiLevel> ai_level_4
    {
      get { return _ai_level_4; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiLevel> _ai_level_5 = new global::System.Collections.Generic.List<dataconfig.AiLevel>();
    [global::ProtoBuf.ProtoMember(7, Name=@"ai_level_5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiLevel> ai_level_5
    {
      get { return _ai_level_5; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiMessage> _ai_message_1 = new global::System.Collections.Generic.List<dataconfig.AiMessage>();
    [global::ProtoBuf.ProtoMember(8, Name=@"ai_message_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiMessage> ai_message_1
    {
      get { return _ai_message_1; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiMessage> _ai_message_2 = new global::System.Collections.Generic.List<dataconfig.AiMessage>();
    [global::ProtoBuf.ProtoMember(9, Name=@"ai_message_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiMessage> ai_message_2
    {
      get { return _ai_message_2; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiMessage> _ai_message_3 = new global::System.Collections.Generic.List<dataconfig.AiMessage>();
    [global::ProtoBuf.ProtoMember(10, Name=@"ai_message_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiMessage> ai_message_3
    {
      get { return _ai_message_3; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.AiMessage> _ai_message_4 = new global::System.Collections.Generic.List<dataconfig.AiMessage>();
    [global::ProtoBuf.ProtoMember(11, Name=@"ai_message_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.AiMessage> ai_message_4
    {
      get { return _ai_message_4; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AI_ELO_ARRAY")]
  public partial class AI_ELO_ARRAY : global::ProtoBuf.IExtensible
  {
    public AI_ELO_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.AI_ELO> _items = new global::System.Collections.Generic.List<dataconfig.AI_ELO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.AI_ELO> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}