//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_projectile_shoot_position.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PROJECTILE_SHOOT_POSITION")]
  public partial class PROJECTILE_SHOOT_POSITION : global::ProtoBuf.IExtensible
  {
    public PROJECTILE_SHOOT_POSITION() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _arenaobject_id = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"arenaobject_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint arenaobject_id
    {
      get { return _arenaobject_id; }
      set { _arenaobject_id = value; }
    }
    private string _animationclip_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"animationclip_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animationclip_name
    {
      get { return _animationclip_name; }
      set { _animationclip_name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _visual_point = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"visual_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> visual_point
    {
      get { return _visual_point; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _shoot_time = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(5, Name=@"shoot_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> shoot_time
    {
      get { return _shoot_time; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _shoot_pos_x = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(6, Name=@"shoot_pos_x", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> shoot_pos_x
    {
      get { return _shoot_pos_x; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _shoot_pos_y = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(7, Name=@"shoot_pos_y", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> shoot_pos_y
    {
      get { return _shoot_pos_y; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _shoot_pos_z = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(8, Name=@"shoot_pos_z", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> shoot_pos_z
    {
      get { return _shoot_pos_z; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PROJECTILE_SHOOT_POSITION_ARRAY")]
  public partial class PROJECTILE_SHOOT_POSITION_ARRAY : global::ProtoBuf.IExtensible
  {
    public PROJECTILE_SHOOT_POSITION_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.PROJECTILE_SHOOT_POSITION> _items = new global::System.Collections.Generic.List<dataconfig.PROJECTILE_SHOOT_POSITION>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.PROJECTILE_SHOOT_POSITION> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}