//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_rune_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RUNE_CONF")]
  public partial class RUNE_CONF : global::ProtoBuf.IExtensible
  {
    public RUNE_CONF() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _stat_addition_id = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stat_addition_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int stat_addition_id
    {
      get { return _stat_addition_id; }
      set { _stat_addition_id = value; }
    }
    private dataconfig.RuneType _rune_type = dataconfig.RuneType.RTYPE_DEFENSE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rune_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.RuneType.RTYPE_DEFENSE)]
    public dataconfig.RuneType rune_type
    {
      get { return _rune_type; }
      set { _rune_type = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.RuneTag> _rune_tag = new global::System.Collections.Generic.List<dataconfig.RuneTag>();
    [global::ProtoBuf.ProtoMember(5, Name=@"rune_tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<dataconfig.RuneTag> rune_tag
    {
      get { return _rune_tag; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RUNE_CONF_ARRAY")]
  public partial class RUNE_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public RUNE_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.RUNE_CONF> _items = new global::System.Collections.Generic.List<dataconfig.RUNE_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.RUNE_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}