//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_attack_sound_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ATTACK_SOUND_CONF")]
  public partial class ATTACK_SOUND_CONF : global::ProtoBuf.IExtensible
  {
    public ATTACK_SOUND_CONF() {}
    
    private uint _key = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _sound = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sound
    {
      get { return _sound; }
      set { _sound = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ATTACK_SOUND_CONF_ARRAY")]
  public partial class ATTACK_SOUND_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public ATTACK_SOUND_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ATTACK_SOUND_CONF> _items = new global::System.Collections.Generic.List<dataconfig.ATTACK_SOUND_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ATTACK_SOUND_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}