//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_level_up_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LEVEL_UP_CONF")]
  public partial class LEVEL_UP_CONF : global::ProtoBuf.IExtensible
  {
    public LEVEL_UP_CONF() {}
    
    private int _id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _exp = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private string _UnLockedFunction = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"UnLockedFunction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UnLockedFunction
    {
      get { return _UnLockedFunction; }
      set { _UnLockedFunction = value; }
    }
    private string _FuncName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"FuncName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FuncName
    {
      get { return _FuncName; }
      set { _FuncName = value; }
    }
    private string _FuncIconPath = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"FuncIconPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FuncIconPath
    {
      get { return _FuncIconPath; }
      set { _FuncIconPath = value; }
    }
    private string _BannedTip = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"BannedTip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BannedTip
    {
      get { return _BannedTip; }
      set { _BannedTip = value; }
    }
    private string _FuncWindowID = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"FuncWindowID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FuncWindowID
    {
      get { return _FuncWindowID; }
      set { _FuncWindowID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LEVEL_UP_CONF_ARRAY")]
  public partial class LEVEL_UP_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public LEVEL_UP_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.LEVEL_UP_CONF> _items = new global::System.Collections.Generic.List<dataconfig.LEVEL_UP_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.LEVEL_UP_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}