//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_stat_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STAT_CONF")]
  public partial class STAT_CONF : global::ProtoBuf.IExtensible
  {
    public STAT_CONF() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private dataconfig.ProtoFScalar _min_value = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"min_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar min_value
    {
      get { return _min_value; }
      set { _min_value = value; }
    }
    private dataconfig.ProtoFScalar _max_value = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"max_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar max_value
    {
      get { return _max_value; }
      set { _max_value = value; }
    }
    private string _display_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"display_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string display_name
    {
      get { return _display_name; }
      set { _display_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STAT_CONF_ARRAY")]
  public partial class STAT_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public STAT_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.STAT_CONF> _items = new global::System.Collections.Generic.List<dataconfig.STAT_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.STAT_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}