//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_task_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TASK_CONF")]
  public partial class TASK_CONF : global::ProtoBuf.IExtensible
  {
    public TASK_CONF() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _GoToWindow = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"GoToWindow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GoToWindow
    {
      get { return _GoToWindow; }
      set { _GoToWindow = value; }
    }
    private string _GoToData = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"GoToData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GoToData
    {
      get { return _GoToData; }
      set { _GoToData = value; }
    }
    private dataconfig.TaskType _task_type = dataconfig.TaskType.TT_DAILY;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"task_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.TaskType.TT_DAILY)]
    public dataconfig.TaskType task_type
    {
      get { return _task_type; }
      set { _task_type = value; }
    }
    private int _open = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int open
    {
      get { return _open; }
      set { _open = value; }
    }
    private int _require_level = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"require_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int require_level
    {
      get { return _require_level; }
      set { _require_level = value; }
    }
    private int _require_task = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"require_task", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int require_task
    {
      get { return _require_task; }
      set { _require_task = value; }
    }
    private int _auto_finish = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"auto_finish", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_finish
    {
      get { return _auto_finish; }
      set { _auto_finish = value; }
    }
    private int _auto_next = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"auto_next", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_next
    {
      get { return _auto_next; }
      set { _auto_next = value; }
    }
    private ulong _time_start = (ulong)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"time_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong time_start
    {
      get { return _time_start; }
      set { _time_start = value; }
    }
    private ulong _time_end = (ulong)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"time_end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong time_end
    {
      get { return _time_end; }
      set { _time_end = value; }
    }
    private uint _duration_time = (uint)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"duration_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint duration_time
    {
      get { return _duration_time; }
      set { _duration_time = value; }
    }
    private int _target_op = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"target_op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int target_op
    {
      get { return _target_op; }
      set { _target_op = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.TASK_CONF.InternalType_target> _target = new global::System.Collections.Generic.List<dataconfig.TASK_CONF.InternalType_target>();
    [global::ProtoBuf.ProtoMember(17, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.TASK_CONF.InternalType_target> target
    {
      get { return _target; }
    }
  
    private dataconfig.GoodsType _RewardGoodsType = dataconfig.GoodsType.GT_NONE;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"RewardGoodsType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.GoodsType.GT_NONE)]
    public dataconfig.GoodsType RewardGoodsType
    {
      get { return _RewardGoodsType; }
      set { _RewardGoodsType = value; }
    }
    private uint _RewardGoodsId = (uint)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"RewardGoodsId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint RewardGoodsId
    {
      get { return _RewardGoodsId; }
      set { _RewardGoodsId = value; }
    }
    private uint _RewardGoodsNum = (uint)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"RewardGoodsNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint RewardGoodsNum
    {
      get { return _RewardGoodsNum; }
      set { _RewardGoodsNum = value; }
    }
    private uint _mail_id = (uint)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_target")]
  public partial class InternalType_target : global::ProtoBuf.IExtensible
  {
    public InternalType_target() {}
    
    private string _type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _data = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TASK_CONF_ARRAY")]
  public partial class TASK_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public TASK_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.TASK_CONF> _items = new global::System.Collections.Generic.List<dataconfig.TASK_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.TASK_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}