//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_ability.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ABILITY")]
  public partial class ABILITY : global::ProtoBuf.IExtensible
  {
    public ABILITY() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _prefab_path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"prefab_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefab_path
    {
      get { return _prefab_path; }
      set { _prefab_path = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _prepare_desc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"prepare_desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prepare_desc
    {
      get { return _prepare_desc; }
      set { _prepare_desc = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _type = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _is_active = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_active", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int is_active
    {
      get { return _is_active; }
      set { _is_active = value; }
    }
    private uint _tips_id = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"tips_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint tips_id
    {
      get { return _tips_id; }
      set { _tips_id = value; }
    }
    private string _cd_name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cd_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cd_name
    {
      get { return _cd_name; }
      set { _cd_name = value; }
    }
    private string _tags = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tags
    {
      get { return _tags; }
      set { _tags = value; }
    }
    private int _priority_level = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"priority_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int priority_level
    {
      get { return _priority_level; }
      set { _priority_level = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _break_precast_status = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"break_precast_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> break_precast_status
    {
      get { return _break_precast_status; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _break_precast_behaviour = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(13, Name=@"break_precast_behaviour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> break_precast_behaviour
    {
      get { return _break_precast_behaviour; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _break_casting_status = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(14, Name=@"break_casting_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> break_casting_status
    {
      get { return _break_casting_status; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _break_casting_behaviour = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(15, Name=@"break_casting_behaviour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> break_casting_behaviour
    {
      get { return _break_casting_behaviour; }
    }
  
    private int _dying_break_deactive_casting = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"dying_break_deactive_casting", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int dying_break_deactive_casting
    {
      get { return _dying_break_deactive_casting; }
      set { _dying_break_deactive_casting = value; }
    }
    private int _stop_move = (int)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"stop_move", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int stop_move
    {
      get { return _stop_move; }
      set { _stop_move = value; }
    }
    private int _change_state = (int)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"change_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int change_state
    {
      get { return _change_state; }
      set { _change_state = value; }
    }
    private int _can_change_to_other_state = (int)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"can_change_to_other_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int can_change_to_other_state
    {
      get { return _can_change_to_other_state; }
      set { _can_change_to_other_state = value; }
    }
    private dataconfig.ProtoFScalar _wait_time = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"wait_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar wait_time
    {
      get { return _wait_time; }
      set { _wait_time = value; }
    }
    private int _if_queue = (int)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"if_queue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int if_queue
    {
      get { return _if_queue; }
      set { _if_queue = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _can_simultaneous_abilities = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(22, Name=@"can_simultaneous_abilities", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> can_simultaneous_abilities
    {
      get { return _can_simultaneous_abilities; }
    }
  
    private int _is_immediately = (int)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"is_immediately", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int is_immediately
    {
      get { return _is_immediately; }
      set { _is_immediately = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _max_charge_num = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(24, Name=@"max_charge_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> max_charge_num
    {
      get { return _max_charge_num; }
    }
  
    private int _min_charge_num = (int)0;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"min_charge_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int min_charge_num
    {
      get { return _min_charge_num; }
      set { _min_charge_num = value; }
    }
    private int _charge_expend = (int)0;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"charge_expend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int charge_expend
    {
      get { return _charge_expend; }
      set { _charge_expend = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _charge_lengths = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(27, Name=@"charge_lengths", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> charge_lengths
    {
      get { return _charge_lengths; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _cd_lengths = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(28, Name=@"cd_lengths", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> cd_lengths
    {
      get { return _cd_lengths; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _interval_cd = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(29, Name=@"interval_cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> interval_cd
    {
      get { return _interval_cd; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _avalible_time = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(30, Name=@"avalible_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> avalible_time
    {
      get { return _avalible_time; }
    }
  
    private int _cost_type = (int)0;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"cost_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int cost_type
    {
      get { return _cost_type; }
      set { _cost_type = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _resource_costs = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(32, Name=@"resource_costs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> resource_costs
    {
      get { return _resource_costs; }
    }
  
    private int _auto_cd = (int)0;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"auto_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_cd
    {
      get { return _auto_cd; }
      set { _auto_cd = value; }
    }
    private dataconfig.ProtoFScalar _return_cd_percent = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"return_cd_percent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar return_cd_percent
    {
      get { return _return_cd_percent; }
      set { _return_cd_percent = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _block_ability_status = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(35, Name=@"block_ability_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> block_ability_status
    {
      get { return _block_ability_status; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ignore_status = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(36, Name=@"ignore_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ignore_status
    {
      get { return _ignore_status; }
    }
  
    private dataconfig.ProtoFScalar _expose_revealer_duration = null;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"expose_revealer_duration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar expose_revealer_duration
    {
      get { return _expose_revealer_duration; }
      set { _expose_revealer_duration = value; }
    }
    private int _need_assistant = (int)0;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"need_assistant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int need_assistant
    {
      get { return _need_assistant; }
      set { _need_assistant = value; }
    }
    private bool _reactive_assistant_before_cast = (bool)false;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"reactive_assistant_before_cast", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool reactive_assistant_before_cast
    {
      get { return _reactive_assistant_before_cast; }
      set { _reactive_assistant_before_cast = value; }
    }
    private bool _reactive_assistant_casting = (bool)false;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"reactive_assistant_casting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool reactive_assistant_casting
    {
      get { return _reactive_assistant_casting; }
      set { _reactive_assistant_casting = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _base_damages = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(41, Name=@"base_damages", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> base_damages
    {
      get { return _base_damages; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _ap_bonus = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(42, Name=@"ap_bonus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> ap_bonus
    {
      get { return _ap_bonus; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _ad_bonus = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(43, Name=@"ad_bonus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> ad_bonus
    {
      get { return _ad_bonus; }
    }
  
    private string _damage_type = "";
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"damage_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string damage_type
    {
      get { return _damage_type; }
      set { _damage_type = value; }
    }
    private dataconfig.ProtoFScalar _after_cast_ani_force_playtime = null;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"after_cast_ani_force_playtime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar after_cast_ani_force_playtime
    {
      get { return _after_cast_ani_force_playtime; }
      set { _after_cast_ani_force_playtime = value; }
    }
    private int _auto_atk_timing = (int)0;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"auto_atk_timing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_atk_timing
    {
      get { return _auto_atk_timing; }
      set { _auto_atk_timing = value; }
    }
    private string _simple_ability = "";
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"simple_ability", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string simple_ability
    {
      get { return _simple_ability; }
      set { _simple_ability = value; }
    }
    private uint _ability_break_type = (uint)0;
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"ability_break_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint ability_break_type
    {
      get { return _ability_break_type; }
      set { _ability_break_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ABILITY_ARRAY")]
  public partial class ABILITY_ARRAY : global::ProtoBuf.IExtensible
  {
    public ABILITY_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ABILITY> _items = new global::System.Collections.Generic.List<dataconfig.ABILITY>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ABILITY> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}