//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_bag_item_tag_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAG_ITEM_TAG_CONF")]
  public partial class BAG_ITEM_TAG_CONF : global::ProtoBuf.IExtensible
  {
    public BAG_ITEM_TAG_CONF() {}
    
    private dataconfig.BagItemTag _type = dataconfig.BagItemTag.BI_NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.BagItemTag.BI_NONE)]
    public dataconfig.BagItemTag type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _tid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAG_ITEM_TAG_CONF_ARRAY")]
  public partial class BAG_ITEM_TAG_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public BAG_ITEM_TAG_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.BAG_ITEM_TAG_CONF> _items = new global::System.Collections.Generic.List<dataconfig.BAG_ITEM_TAG_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.BAG_ITEM_TAG_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}