//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_game_resource_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAME_RESOURCE_CONF")]
  public partial class GAME_RESOURCE_CONF : global::ProtoBuf.IExtensible
  {
    public GAME_RESOURCE_CONF() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _tid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private string _iconPath = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iconPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string iconPath
    {
      get { return _iconPath; }
      set { _iconPath = value; }
    }
    private int _textColor = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"textColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int textColor
    {
      get { return _textColor; }
      set { _textColor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAME_RESOURCE_CONF_ARRAY")]
  public partial class GAME_RESOURCE_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public GAME_RESOURCE_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.GAME_RESOURCE_CONF> _items = new global::System.Collections.Generic.List<dataconfig.GAME_RESOURCE_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.GAME_RESOURCE_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}