//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_signal_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SIGNAL_CONF")]
  public partial class SIGNAL_CONF : global::ProtoBuf.IExtensible
  {
    public SIGNAL_CONF() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private string _text_type = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"text_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text_type
    {
      get { return _text_type; }
      set { _text_type = value; }
    }
    private string _text_group = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"text_group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text_group
    {
      get { return _text_group; }
      set { _text_group = value; }
    }
    private uint _default_order = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"default_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint default_order
    {
      get { return _default_order; }
      set { _default_order = value; }
    }
    private int _soundID = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"soundID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int soundID
    {
      get { return _soundID; }
      set { _soundID = value; }
    }
    private string _signal_type = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"signal_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string signal_type
    {
      get { return _signal_type; }
      set { _signal_type = value; }
    }
    private bool _is_myTeam = (bool)false;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is_myTeam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool is_myTeam
    {
      get { return _is_myTeam; }
      set { _is_myTeam = value; }
    }
    private string _prefab = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"prefab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefab
    {
      get { return _prefab; }
      set { _prefab = value; }
    }
    private string _effect_target = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"effect_target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effect_target
    {
      get { return _effect_target; }
      set { _effect_target = value; }
    }
    private string _minimap_effect = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"minimap_effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string minimap_effect
    {
      get { return _minimap_effect; }
      set { _minimap_effect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SIGNAL_CONF_ARRAY")]
  public partial class SIGNAL_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public SIGNAL_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.SIGNAL_CONF> _items = new global::System.Collections.Generic.List<dataconfig.SIGNAL_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.SIGNAL_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}