//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_rune_recommend.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RUNE_RECOMMEND")]
  public partial class RUNE_RECOMMEND : global::ProtoBuf.IExtensible
  {
    public RUNE_RECOMMEND() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.RUNE_RECOMMEND.InternalType_RecommendStruct> _RecommendStruct = new global::System.Collections.Generic.List<dataconfig.RUNE_RECOMMEND.InternalType_RecommendStruct>();
    [global::ProtoBuf.ProtoMember(2, Name=@"RecommendStruct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.RUNE_RECOMMEND.InternalType_RecommendStruct> RecommendStruct
    {
      get { return _RecommendStruct; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_RecommendStruct")]
  public partial class InternalType_RecommendStruct : global::ProtoBuf.IExtensible
  {
    public InternalType_RecommendStruct() {}
    
    private int _level = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _rune_id_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rune_id_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> rune_id_list
    {
      get { return _rune_id_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RUNE_RECOMMEND_ARRAY")]
  public partial class RUNE_RECOMMEND_ARRAY : global::ProtoBuf.IExtensible
  {
    public RUNE_RECOMMEND_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.RUNE_RECOMMEND> _items = new global::System.Collections.Generic.List<dataconfig.RUNE_RECOMMEND>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.RUNE_RECOMMEND> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}