//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_user_guide_arena_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"USER_GUIDE_ARENA_CONF")]
  public partial class USER_GUIDE_ARENA_CONF : global::ProtoBuf.IExtensible
  {
    public USER_GUIDE_ARENA_CONF() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _creatObjName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"creatObjName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string creatObjName
    {
      get { return _creatObjName; }
      set { _creatObjName = value; }
    }
    private uint _objectId = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"objectId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint objectId
    {
      get { return _objectId; }
      set { _objectId = value; }
    }
    private uint _skinId = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint skinId
    {
      get { return _skinId; }
      set { _skinId = value; }
    }
    private uint _uin = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _position = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(7, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> position
    {
      get { return _position; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _direction = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(8, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> direction
    {
      get { return _direction; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ProtoFScalar> _size = new global::System.Collections.Generic.List<dataconfig.ProtoFScalar>();
    [global::ProtoBuf.ProtoMember(9, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ProtoFScalar> size
    {
      get { return _size; }
    }
  
    private bool _attackLocalHero = (bool)false;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"attackLocalHero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool attackLocalHero
    {
      get { return _attackLocalHero; }
      set { _attackLocalHero = value; }
    }
    private bool _rebornable = (bool)false;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rebornable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool rebornable
    {
      get { return _rebornable; }
      set { _rebornable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"USER_GUIDE_ARENA_CONF_ARRAY")]
  public partial class USER_GUIDE_ARENA_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public USER_GUIDE_ARENA_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.USER_GUIDE_ARENA_CONF> _items = new global::System.Collections.Generic.List<dataconfig.USER_GUIDE_ARENA_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.USER_GUIDE_ARENA_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}