//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_reward_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"REWARD_CONF")]
  public partial class REWARD_CONF : global::ProtoBuf.IExtensible
  {
    public REWARD_CONF() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private dataconfig.RewardType _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public dataconfig.RewardType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Icon = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _DisplayName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DisplayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DisplayName
    {
      get { return _DisplayName; }
      set { _DisplayName = value; }
    }
    private string _Description = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }
    private int _DropChance = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"DropChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int DropChance
    {
      get { return _DropChance; }
      set { _DropChance = value; }
    }
    private int _DropRound = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"DropRound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int DropRound
    {
      get { return _DropRound; }
      set { _DropRound = value; }
    }
    private readonly global::System.Collections.Generic.List<dataconfig.REWARD_CONF.InternalType_RewardItem> _RewardItem = new global::System.Collections.Generic.List<dataconfig.REWARD_CONF.InternalType_RewardItem>();
    [global::ProtoBuf.ProtoMember(8, Name=@"RewardItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.REWARD_CONF.InternalType_RewardItem> RewardItem
    {
      get { return _RewardItem; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_RewardItem")]
  public partial class InternalType_RewardItem : global::ProtoBuf.IExtensible
  {
    public InternalType_RewardItem() {}
    
    private dataconfig.GoodsType _Type = dataconfig.GoodsType.GT_NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(dataconfig.GoodsType.GT_NONE)]
    public dataconfig.GoodsType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private uint _Id = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private uint _Count = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private int _DropWeight = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DropWeight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int DropWeight
    {
      get { return _DropWeight; }
      set { _DropWeight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"REWARD_CONF_ARRAY")]
  public partial class REWARD_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public REWARD_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.REWARD_CONF> _items = new global::System.Collections.Generic.List<dataconfig.REWARD_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.REWARD_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}