//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_arena_tips.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ARENA_TIPS")]
  public partial class ARENA_TIPS : global::ProtoBuf.IExtensible
  {
    public ARENA_TIPS() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _static_params = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"static_params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> static_params
    {
      get { return _static_params; }
    }
  
    private string _description_tip = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"description_tip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description_tip
    {
      get { return _description_tip; }
      set { _description_tip = value; }
    }
    private string _tips_lua = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tips_lua", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tips_lua
    {
      get { return _tips_lua; }
      set { _tips_lua = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _position = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> position
    {
      get { return _position; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _cd = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> cd
    {
      get { return _cd; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _manaCost = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(8, Name=@"manaCost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> manaCost
    {
      get { return _manaCost; }
    }
  
    private readonly global::System.Collections.Generic.List<dataconfig.ARENA_TIPS.InternalType_stats> _stats = new global::System.Collections.Generic.List<dataconfig.ARENA_TIPS.InternalType_stats>();
    [global::ProtoBuf.ProtoMember(9, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ARENA_TIPS.InternalType_stats> stats
    {
      get { return _stats; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InternalType_stats")]
  public partial class InternalType_stats : global::ProtoBuf.IExtensible
  {
    public InternalType_stats() {}
    
    private string _statName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"statName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string statName
    {
      get { return _statName; }
      set { _statName = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _stat_per_level = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stat_per_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> stat_per_level
    {
      get { return _stat_per_level; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ARENA_TIPS_ARRAY")]
  public partial class ARENA_TIPS_ARRAY : global::ProtoBuf.IExtensible
  {
    public ARENA_TIPS_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.ARENA_TIPS> _items = new global::System.Collections.Generic.List<dataconfig.ARENA_TIPS>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.ARENA_TIPS> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}