//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_ui_config.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UI_CONFIG")]
  public partial class UI_CONFIG : global::ProtoBuf.IExtensible
  {
    public UI_CONFIG() {}
    
    private string _windowName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"windowName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string windowName
    {
      get { return _windowName; }
      set { _windowName = value; }
    }
    private string _windowTitle = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"windowTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string windowTitle
    {
      get { return _windowTitle; }
      set { _windowTitle = value; }
    }
    private string _prefabPath = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"prefabPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefabPath
    {
      get { return _prefabPath; }
      set { _prefabPath = value; }
    }
    private string _resourcePath = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resourcePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resourcePath
    {
      get { return _resourcePath; }
      set { _resourcePath = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _uiType = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uiType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uiType
    {
      get { return _uiType; }
      set { _uiType = value; }
    }
    private string _bg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bg
    {
      get { return _bg; }
      set { _bg = value; }
    }
    private string _topbar = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"topbar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string topbar
    {
      get { return _topbar; }
      set { _topbar = value; }
    }
    private int _cacheMode = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cacheMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int cacheMode
    {
      get { return _cacheMode; }
      set { _cacheMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UI_CONFIG_ARRAY")]
  public partial class UI_CONFIG_ARRAY : global::ProtoBuf.IExtensible
  {
    public UI_CONFIG_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.UI_CONFIG> _items = new global::System.Collections.Generic.List<dataconfig.UI_CONFIG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.UI_CONFIG> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}