//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_day_night_conf.proto
// Note: requires additional types generated from: ProtoFScalar.proto
// Note: requires additional types generated from: xls_enum.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAY_NIGHT_CONF")]
  public partial class DAY_NIGHT_CONF : global::ProtoBuf.IExtensible
  {
    public DAY_NIGHT_CONF() {}
    
    private dataconfig.ProtoFScalar _gamePrepare = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gamePrepare", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar gamePrepare
    {
      get { return _gamePrepare; }
      set { _gamePrepare = value; }
    }
    private dataconfig.ProtoFScalar _dayBegin = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dayBegin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar dayBegin
    {
      get { return _dayBegin; }
      set { _dayBegin = value; }
    }
    private dataconfig.ProtoFScalar _dayDuration = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dayDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar dayDuration
    {
      get { return _dayDuration; }
      set { _dayDuration = value; }
    }
    private dataconfig.ProtoFScalar _nightBegin = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nightBegin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar nightBegin
    {
      get { return _nightBegin; }
      set { _nightBegin = value; }
    }
    private dataconfig.ProtoFScalar _nightDuration = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nightDuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar nightDuration
    {
      get { return _nightDuration; }
      set { _nightDuration = value; }
    }
    private dataconfig.ProtoFScalar _dayViewRange = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dayViewRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar dayViewRange
    {
      get { return _dayViewRange; }
      set { _dayViewRange = value; }
    }
    private dataconfig.ProtoFScalar _nightViewRange = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"nightViewRange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar nightViewRange
    {
      get { return _nightViewRange; }
      set { _nightViewRange = value; }
    }
    private dataconfig.ProtoFScalar _dayTowerAtkPow = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dayTowerAtkPow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar dayTowerAtkPow
    {
      get { return _dayTowerAtkPow; }
      set { _dayTowerAtkPow = value; }
    }
    private dataconfig.ProtoFScalar _nightTowerAtkPow = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nightTowerAtkPow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public dataconfig.ProtoFScalar nightTowerAtkPow
    {
      get { return _nightTowerAtkPow; }
      set { _nightTowerAtkPow = value; }
    }
    private uint _dayBuffID = (uint)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dayBuffID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint dayBuffID
    {
      get { return _dayBuffID; }
      set { _dayBuffID = value; }
    }
    private uint _nightBuffID = (uint)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nightBuffID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint nightBuffID
    {
      get { return _nightBuffID; }
      set { _nightBuffID = value; }
    }
    private int _dayEffectID = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"dayEffectID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int dayEffectID
    {
      get { return _dayEffectID; }
      set { _dayEffectID = value; }
    }
    private int _nightEffectID = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"nightEffectID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int nightEffectID
    {
      get { return _nightEffectID; }
      set { _nightEffectID = value; }
    }
    private int _nightTowerArmorChange = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"nightTowerArmorChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int nightTowerArmorChange
    {
      get { return _nightTowerArmorChange; }
      set { _nightTowerArmorChange = value; }
    }
    private uint _isDayTowerArmorRestore = (uint)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"isDayTowerArmorRestore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint isDayTowerArmorRestore
    {
      get { return _isDayTowerArmorRestore; }
      set { _isDayTowerArmorRestore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAY_NIGHT_CONF_ARRAY")]
  public partial class DAY_NIGHT_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public DAY_NIGHT_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.DAY_NIGHT_CONF> _items = new global::System.Collections.Generic.List<dataconfig.DAY_NIGHT_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.DAY_NIGHT_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}