//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: xls_enum.proto
namespace dataconfig
{
    [global::ProtoBuf.ProtoContract(Name=@"GoodsType")]
    public enum GoodsType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_NONE", Value=0)]
      GT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_COIN", Value=1)]
      GT_COIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_COUPON", Value=2)]
      GT_COUPON = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_DIAMOND", Value=3)]
      GT_DIAMOND = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_CHAMPION", Value=4)]
      GT_CHAMPION = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_BAGITEM", Value=5)]
      GT_BAGITEM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_AVATAR", Value=6)]
      GT_AVATAR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_REWARD", Value=7)]
      GT_REWARD = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_TASKSCORE", Value=8)]
      GT_TASKSCORE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_ACHIEVEMENT", Value=9)]
      GT_ACHIEVEMENT = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_RUNE_SLICE", Value=10)]
      GT_RUNE_SLICE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_PLAYER_EXP", Value=11)]
      GT_PLAYER_EXP = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_ACHIEVEMENT_LV", Value=12)]
      GT_ACHIEVEMENT_LV = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_PLAYER_LV", Value=13)]
      GT_PLAYER_LV = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RewardType")]
    public enum RewardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_GIFT", Value=1)]
      RT_GIFT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_DROP", Value=2)]
      RT_DROP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OpType")]
    public enum OpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OT_ADD", Value=1)]
      OT_ADD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OT_SUB", Value=2)]
      OT_SUB = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OT_SET", Value=3)]
      OT_SET = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MallItemTag")]
    public enum MallItemTag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MI_RECOMMEND", Value=1)]
      MI_RECOMMEND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MI_NEWSALE", Value=2)]
      MI_NEWSALE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MI_NEWBIE", Value=3)]
      MI_NEWBIE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MI_DAILY", Value=4)]
      MI_DAILY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MI_HOTSALE", Value=5)]
      MI_HOTSALE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MI_STRONG_NEWSALE", Value=6)]
      MI_STRONG_NEWSALE = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MallAchievingType")]
    public enum MallAchievingType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MA_NORMAL_SALE", Value=1)]
      MA_NORMAL_SALE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MA_TIME_LIMIT_SALE", Value=2)]
      MA_TIME_LIMIT_SALE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MA_ACTIVITY_LIMIT", Value=3)]
      MA_ACTIVITY_LIMIT = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskType")]
    public enum TaskType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_DAILY", Value=1)]
      TT_DAILY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_DAILY_SCORE", Value=2)]
      TT_DAILY_SCORE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_WEEKLY_SCORE", Value=4)]
      TT_WEEKLY_SCORE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ACHIEVEMENT", Value=8)]
      TT_ACHIEVEMENT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ACHIEVEMENT_LEVEL", Value=16)]
      TT_ACHIEVEMENT_LEVEL = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_PLAYER_LEVEL", Value=32)]
      TT_PLAYER_LEVEL = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_ACCOUNT_BIND", Value=64)]
      TT_ACCOUNT_BIND = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_LEVEL_FOLLOWING", Value=128)]
      TT_LEVEL_FOLLOWING = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_SPRINT_LEVEL", Value=256)]
      TT_SPRINT_LEVEL = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_CYCLE_LOGIN", Value=512)]
      TT_CYCLE_LOGIN = 512
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskStoreType")]
    public enum TaskStoreType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TST_DAILY", Value=1)]
      TST_DAILY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TST_WEEKLY", Value=2)]
      TST_WEEKLY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TST_MONTHLY", Value=3)]
      TST_MONTHLY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TST_PERSISTENT", Value=4)]
      TST_PERSISTENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TST_CHECK", Value=5)]
      TST_CHECK = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BagItemType")]
    public enum BagItemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_ALL", Value=1)]
      BI_ALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_LAST", Value=2)]
      BI_LAST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_ITEM", Value=3)]
      BI_ITEM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_REWARD", Value=4)]
      BI_REWARD = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_CARD", Value=5)]
      BI_CARD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_RUNE", Value=6)]
      BI_RUNE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_ARENA_ITEM", Value=7)]
      BI_ARENA_ITEM = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_NAME_CARD", Value=8)]
      BI_NAME_CARD = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_AVATAR_CARD", Value=9)]
      BI_AVATAR_CARD = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_CHAMPION_CARD", Value=10)]
      BI_CHAMPION_CARD = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_EXP_CARD_TIME", Value=11)]
      BI_EXP_CARD_TIME = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_MONEY_CARD_TIME", Value=12)]
      BI_MONEY_CARD_TIME = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_EXP_CARD_TIMES", Value=13)]
      BI_EXP_CARD_TIMES = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_MONEY_CARD_TIMES", Value=14)]
      BI_MONEY_CARD_TIMES = 14
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BagItemTag")]
    public enum BagItemTag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_NONE", Value=0)]
      BI_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_HERO_CARD", Value=1)]
      BI_HERO_CARD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BI_SKIN_CARD", Value=2)]
      BI_SKIN_CARD = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemRarity")]
    public enum ItemRarity
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"IR_COMMON", Value=1)]
      IR_COMMON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IR_ADVANCED", Value=2)]
      IR_ADVANCED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IR_RARE", Value=3)]
      IR_RARE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IR_LEGENDARY", Value=4)]
      IR_LEGENDARY = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RuneType")]
    public enum RuneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTYPE_DEFENSE", Value=1)]
      RTYPE_DEFENSE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTYPE_ATTACK", Value=2)]
      RTYPE_ATTACK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTYPE_FEATRUES", Value=3)]
      RTYPE_FEATRUES = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RuneTag")]
    public enum RuneTag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_ATK", Value=1)]
      RT_ATK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_HP", Value=2)]
      RT_HP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_DEFENSE", Value=3)]
      RT_DEFENSE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_FEATRUES", Value=4)]
      RT_FEATRUES = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_BLOOD", Value=5)]
      RT_BLOOD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_ATTACK_SPEED", Value=6)]
      RT_ATTACK_SPEED = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_CRIT", Value=7)]
      RT_CRIT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_PENETRATION", Value=8)]
      RT_PENETRATION = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailType")]
    public enum MailType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_SYSTEM", Value=1)]
      MT_TYPE_SYSTEM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_MESSAGE", Value=2)]
      MT_TYPE_MESSAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_FRIEND_INVITE", Value=3)]
      MT_TYPE_FRIEND_INVITE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_FRIEND_INVITERSP", Value=4)]
      MT_TYPE_FRIEND_INVITERSP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_FRIEND_SEND", Value=5)]
      MT_TYPE_FRIEND_SEND = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_ASKFOR", Value=6)]
      MT_TYPE_ASKFOR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_FRIEND_SEND_COIN", Value=7)]
      MT_TYPE_FRIEND_SEND_COIN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MT_TYPE_MODIFY_PLAYER_IDIP", Value=8)]
      MT_TYPE_MODIFY_PLAYER_IDIP = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailConditionType")]
    public enum MailConditionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MCT_TYPE_ALL", Value=1)]
      MCT_TYPE_ALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MCT_TYPE_SCOPE", Value=2)]
      MCT_TYPE_SCOPE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MCT_TYPE_EVENT", Value=3)]
      MCT_TYPE_EVENT = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"UserGuideActionType")]
    public enum UserGuideActionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIALOGUE", Value=1)]
      DIALOGUE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIPS", Value=2)]
      TIPS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_TOUCH", Value=3)]
      FORCE_TOUCH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PICTURE", Value=4)]
      PICTURE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_POS", Value=5)]
      MOVE_POS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KILL_ITEM", Value=6)]
      KILL_ITEM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPAWN_CREEP", Value=7)]
      SPAWN_CREEP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPAWN_HERO", Value=8)]
      SPAWN_HERO = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPAWN_WALL", Value=9)]
      SPAWN_WALL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_OBJ", Value=10)]
      DELETE_OBJ = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_WALL", Value=11)]
      DELETE_WALL = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_CAMERA", Value=12)]
      MOVE_CAMERA = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TERMINAL", Value=13)]
      TERMINAL = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIN", Value=14)]
      MAIN = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEQUENCE", Value=15)]
      SEQUENCE = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVIE", Value=16)]
      MOVIE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANIMATION", Value=17)]
      ANIMATION = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET_NAME", Value=18)]
      SET_NAME = 18
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"UserGuideTriggerType")]
    public enum UserGuideTriggerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL_UP", Value=1)]
      LEVEL_UP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_TO_TARGET", Value=2)]
      MOVE_TO_TARGET = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KILL", Value=3)]
      KILL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT", Value=4)]
      EVENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEALTH_PERCENT", Value=5)]
      HEALTH_PERCENT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISTANCE", Value=6)]
      DISTANCE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=7)]
      GOLD = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_OVER", Value=8)]
      GAME_OVER = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HeroPositionType")]
    public enum HeroPositionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_NONE", Value=0)]
      HP_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_TANK", Value=1)]
      HP_TANK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_FIGHTER", Value=2)]
      HP_FIGHTER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_ASSASSIN", Value=3)]
      HP_ASSASSIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_MAGE", Value=4)]
      HP_MAGE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_SHOOTER", Value=5)]
      HP_SHOOTER = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP_SUPPORT", Value=6)]
      HP_SUPPORT = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AiLevel")]
    public enum AiLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_NONE", Value=0)]
      AL_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_EASY", Value=1)]
      AL_EASY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_NORMAL", Value=2)]
      AL_NORMAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_HARD", Value=3)]
      AL_HARD = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AiMessage")]
    public enum AiMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AM_NONE", Value=0)]
      AM_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AM_LEADER", Value=1)]
      AM_LEADER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AM_FRIEND", Value=2)]
      AM_FRIEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AM_SELFISH", Value=3)]
      AM_SELFISH = 3
    }
  
}