import os
ecode = os.system("python checker/check.py")
if ecode != 0:
    exit(ecode)
    
os.system("python xlsc.py global_config GLOBAL_CONFIG")
os.system("python xlsc.py ability ABILITY")
os.system("python xlsc.py ability ABILITY_INPUT")
os.system("python xlsc.py arena_mode ARENA_MODE_CONF")
os.system("python xlsc.py arena_mode ARENA_MODE_MAPTYPE_CONF")
os.system("python xlsc.py arena_mode ARENA_MODE_GAMEMODE_CONF")
os.system("python xlsc.py arena_mode ARENA_MODE_CONF")
os.system("python xlsc.py arena_object ARENA_OBJECT_CONF")
os.system("python xlsc.py arena_type ARENA_TYPE_CONF")
os.system("python xlsc.py attack ATTACK_CONF")
os.system("python xlsc.py buff BUFF")
os.system("python xlsc.py buff BUFF_TAG")
os.system("python xlsc.py combo_ability COMBO_ABILITY")
os.system("python xlsc.py projectile PROJECTILE_CONF")
os.system("python xlsc.py projectile PROJECTILE_SHOOT_POSITION")
os.system("python xlsc.py stat STAT_CONF")
os.system("python xlsc.py stat BASE_STATS")
os.system("python xlsc.py stat RESOURCE_CONF")
os.system("python xlsc.py skin SKIN_CONF")
os.system("python xlsc.py item ITEM_CONF")
os.system("python xlsc.py item RECOMMEND_ITEM_CONF")
os.system("python xlsc.py attack_sound_tmp ATTACK_SOUND_CONF")
os.system("python xlsc.py localization LOCALIZATION_CONF")
os.system("python xlsc.py signal SIGNAL_CONF")
os.system("python xlsc.py user_guide USER_GUIDE_CONF")
os.system("python xlsc.py arena_tips ARENA_TIPS")

os.system("python xlsc_precompile.py")
