//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: c2s_cmd.proto
namespace moba_protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ZoneSvrCmd")]
    public enum ZoneSvrCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LOGIN_REQ", Value=257)]
      ZONE_LOGIN_REQ = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LOGIN_RSP", Value=258)]
      ZONE_LOGIN_RSP = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_REGISTER_REQ", Value=259)]
      ZONE_REGISTER_REQ = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_REGISTER_RSP", Value=260)]
      ZONE_REGISTER_RSP = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_NAME_GET_REQ", Value=261)]
      ZONE_NAME_GET_REQ = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_NAME_GET_RSP", Value=262)]
      ZONE_NAME_GET_RSP = 262,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_NAME_CHANGE_REQ", Value=263)]
      ZONE_NAME_CHANGE_REQ = 263,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_NAME_CHANGE_RSP", Value=264)]
      ZONE_NAME_CHANGE_RSP = 264,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CREATE_REQ", Value=265)]
      ZONE_ROOM_CREATE_REQ = 265,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CREATE_RSP", Value=266)]
      ZONE_ROOM_CREATE_RSP = 266,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_INVITE_FRIEND_REQ", Value=267)]
      ZONE_ROOM_INVITE_FRIEND_REQ = 267,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_INVITE_FRIEND_RSP", Value=268)]
      ZONE_ROOM_INVITE_FRIEND_RSP = 268,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_INVITE_INNER_REQ", Value=269)]
      ZONE_ROOM_INVITE_INNER_REQ = 269,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_INVITE_INNER_RSP", Value=270)]
      ZONE_ROOM_INVITE_INNER_RSP = 270,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_JOIN_REQ", Value=272)]
      ZONE_ROOM_JOIN_REQ = 272,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_JOIN_RSP", Value=273)]
      ZONE_ROOM_JOIN_RSP = 273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_EXIT_REQ", Value=274)]
      ZONE_ROOM_EXIT_REQ = 274,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_EXIT_RSP", Value=275)]
      ZONE_ROOM_EXIT_RSP = 275,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_ADD_ROBOT_REQ", Value=276)]
      ZONE_ROOM_ADD_ROBOT_REQ = 276,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_ADD_ROBOT_RSP", Value=277)]
      ZONE_ROOM_ADD_ROBOT_RSP = 277,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CHANGE_TEAM_POS_REQ", Value=278)]
      ZONE_ROOM_CHANGE_TEAM_POS_REQ = 278,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CHANGE_TEAM_POS_RSP", Value=279)]
      ZONE_ROOM_CHANGE_TEAM_POS_RSP = 279,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_DEL_PLAYER_REQ", Value=280)]
      ZONE_ROOM_DEL_PLAYER_REQ = 280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_DEL_PLAYER_RSP", Value=281)]
      ZONE_ROOM_DEL_PLAYER_RSP = 281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GAME_START_REQ", Value=282)]
      ZONE_GAME_START_REQ = 282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GAME_START_RSP", Value=283)]
      ZONE_GAME_START_RSP = 283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_CHAMPION_REQ", Value=284)]
      ZONE_SELECT_CHAMPION_REQ = 284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_CHAMPION_RSP", Value=285)]
      ZONE_SELECT_CHAMPION_RSP = 285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CONFIRM_CHAMPION_REQ", Value=286)]
      ZONE_CONFIRM_CHAMPION_REQ = 286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CONFIRM_CHAMPION_RSP", Value=287)]
      ZONE_CONFIRM_CHAMPION_RSP = 287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_AVATAR_REQ", Value=288)]
      ZONE_SELECT_AVATAR_REQ = 288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_AVATAR_RSP", Value=289)]
      ZONE_SELECT_AVATAR_RSP = 289,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_REQ", Value=290)]
      ZONE_MATCH_REQ = 290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_RSP", Value=291)]
      ZONE_MATCH_RSP = 291,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_CANCEL_REQ", Value=292)]
      ZONE_MATCH_CANCEL_REQ = 292,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_CANCEL_RSP", Value=293)]
      ZONE_MATCH_CANCEL_RSP = 293,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_CONFIRM_REQ", Value=294)]
      ZONE_MATCH_CONFIRM_REQ = 294,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_CONFIRM_RSP", Value=295)]
      ZONE_MATCH_CONFIRM_RSP = 295,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CHAT_REQ", Value=296)]
      ZONE_ROOM_CHAT_REQ = 296,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CHAT_RSP", Value=297)]
      ZONE_ROOM_CHAT_RSP = 297,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_HEARTBEAT_REQ", Value=298)]
      ZONE_HEARTBEAT_REQ = 298,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_HEARTBEAT_RSP", Value=299)]
      ZONE_HEARTBEAT_RSP = 299,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_LIST_REQ", Value=300)]
      ZONE_LIVE_LIST_REQ = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_LIST_RSP", Value=301)]
      ZONE_LIVE_LIST_RSP = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_WATCH_REQ", Value=302)]
      ZONE_LIVE_WATCH_REQ = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_WATCH_RSP", Value=303)]
      ZONE_LIVE_WATCH_RSP = 303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_STATUS_CLEAN_REQ", Value=307)]
      ZONE_STATUS_CLEAN_REQ = 307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_STATUS_CLEAN_RSP", Value=308)]
      ZONE_STATUS_CLEAN_RSP = 308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_GAME_RESULT_REQ", Value=309)]
      ZONE_GET_GAME_RESULT_REQ = 309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_GAME_RESULT_RSP", Value=310)]
      ZONE_GET_GAME_RESULT_RSP = 310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAT_FRIEND_LIST_REQ", Value=311)]
      ZONE_GET_PLAT_FRIEND_LIST_REQ = 311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAT_FRIEND_LIST_RSP", Value=312)]
      ZONE_GET_PLAT_FRIEND_LIST_RSP = 312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TEAM_MATCH_CREATE_REQ", Value=313)]
      ZONE_TEAM_MATCH_CREATE_REQ = 313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TEAM_MATCH_CREATE_RSP", Value=314)]
      ZONE_TEAM_MATCH_CREATE_RSP = 314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_START_TEAM_MATCH_REQ", Value=315)]
      ZONE_START_TEAM_MATCH_REQ = 315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_START_TEAM_MATCH_RSP", Value=316)]
      ZONE_START_TEAM_MATCH_RSP = 316,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_BAG_REQ", Value=317)]
      ZONE_GET_BAG_REQ = 317,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_BAG_RSP", Value=318)]
      ZONE_GET_BAG_RSP = 318,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_USE_BAG_ITEM_REQ", Value=320)]
      ZONE_USE_BAG_ITEM_REQ = 320,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_USE_BAG_ITEM_RSP", Value=321)]
      ZONE_USE_BAG_ITEM_RSP = 321,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELL_BAG_ITEM_REQ", Value=322)]
      ZONE_SELL_BAG_ITEM_REQ = 322,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELL_BAG_ITEM_RSP", Value=323)]
      ZONE_SELL_BAG_ITEM_RSP = 323,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_BUFF_GET_REQ", Value=324)]
      ZONE_CLI_BUFF_GET_REQ = 324,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_BUFF_GET_RSP", Value=325)]
      ZONE_CLI_BUFF_GET_RSP = 325,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_BUFF_SET_REQ", Value=326)]
      ZONE_CLI_BUFF_SET_REQ = 326,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_BUFF_SET_RSP", Value=327)]
      ZONE_CLI_BUFF_SET_RSP = 327,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_GET_LIST_REQ", Value=330)]
      ZONE_MAIL_GET_LIST_REQ = 330,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_GET_LIST_RSP", Value=331)]
      ZONE_MAIL_GET_LIST_RSP = 331,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_GET_REQ", Value=332)]
      ZONE_MAIL_GET_REQ = 332,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_GET_RSP", Value=333)]
      ZONE_MAIL_GET_RSP = 333,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_DEL_REQ", Value=334)]
      ZONE_MAIL_DEL_REQ = 334,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_DEL_RSP", Value=335)]
      ZONE_MAIL_DEL_RSP = 335,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_MOD_STATUS_REQ", Value=336)]
      ZONE_MAIL_MOD_STATUS_REQ = 336,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_MOD_STATUS_RSP", Value=337)]
      ZONE_MAIL_MOD_STATUS_RSP = 337,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_GET_ATTACHMENT_REQ", Value=338)]
      ZONE_MAIL_GET_ATTACHMENT_REQ = 338,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_GET_ATTACHMENT_RSP", Value=339)]
      ZONE_MAIL_GET_ATTACHMENT_RSP = 339,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ADD_CHAMPION_REQ", Value=340)]
      ZONE_ADD_CHAMPION_REQ = 340,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ADD_CHAMPION_RSP", Value=341)]
      ZONE_ADD_CHAMPION_RSP = 341,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TASK_QUERY_REQ", Value=342)]
      ZONE_TASK_QUERY_REQ = 342,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TASK_QUERY_RSP", Value=343)]
      ZONE_TASK_QUERY_RSP = 343,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TASK_REWARD_REQ", Value=344)]
      ZONE_TASK_REWARD_REQ = 344,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TASK_REWARD_RSP", Value=345)]
      ZONE_TASK_REWARD_RSP = 345,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_SEND_REQ", Value=346)]
      ZONE_MAIL_SEND_REQ = 346,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MAIL_SEND_RSP", Value=347)]
      ZONE_MAIL_SEND_RSP = 347,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_RECV_MAIL_ATTACHMENTS_REQ", Value=350)]
      ZONE_RECV_MAIL_ATTACHMENTS_REQ = 350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_RECV_MAIL_ATTACHMENTS_RSP", Value=351)]
      ZONE_RECV_MAIL_ATTACHMENTS_RSP = 351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_SET_INT_REQ", Value=352)]
      ZONE_CLI_PREF_SET_INT_REQ = 352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_SET_INT_RSP", Value=353)]
      ZONE_CLI_PREF_SET_INT_RSP = 353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_SET_LIST_REQ", Value=354)]
      ZONE_CLI_PREF_SET_LIST_REQ = 354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_SET_LIST_RSP", Value=355)]
      ZONE_CLI_PREF_SET_LIST_RSP = 355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_DELETE_REQ", Value=356)]
      ZONE_CLI_PREF_DELETE_REQ = 356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_DELETE_RSP", Value=357)]
      ZONE_CLI_PREF_DELETE_RSP = 357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_SUMMOUR_ABILITY_REQ", Value=358)]
      ZONE_SELECT_SUMMOUR_ABILITY_REQ = 358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_SUMMOUR_ABILITY_RSP", Value=359)]
      ZONE_SELECT_SUMMOUR_ABILITY_RSP = 359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_RUNE_REQ", Value=360)]
      ZONE_GET_RUNE_REQ = 360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_RUNE_RSP", Value=361)]
      ZONE_GET_RUNE_RSP = 361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ADD_RUNE_PAGE_REQ", Value=362)]
      ZONE_ADD_RUNE_PAGE_REQ = 362,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ADD_RUNE_PAGE_RSP", Value=363)]
      ZONE_ADD_RUNE_PAGE_RSP = 363,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_UNLOCK_RUNE_SLOT_REQ", Value=364)]
      ZONE_UNLOCK_RUNE_SLOT_REQ = 364,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_UNLOCK_RUNE_SLOT_RSP", Value=365)]
      ZONE_UNLOCK_RUNE_SLOT_RSP = 365,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_UPDATE_RUNE_PAGE_NAME_REQ", Value=366)]
      ZONE_UPDATE_RUNE_PAGE_NAME_REQ = 366,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_UPDATE_RUNE_PAGE_NAME_RSP", Value=367)]
      ZONE_UPDATE_RUNE_PAGE_NAME_RSP = 367,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MALL_BUY_ITEM_REQ", Value=368)]
      ZONE_MALL_BUY_ITEM_REQ = 368,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MALL_BUY_ITEM_RSP", Value=369)]
      ZONE_MALL_BUY_ITEM_RSP = 369,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_RUNE_PAGE_REQ", Value=370)]
      ZONE_SELECT_RUNE_PAGE_REQ = 370,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SELECT_RUNE_PAGE_RSP", Value=371)]
      ZONE_SELECT_RUNE_PAGE_RSP = 371,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_RUNE_PAGE_REQ", Value=372)]
      ZONE_SET_RUNE_PAGE_REQ = 372,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_RUNE_PAGE_RSP", Value=373)]
      ZONE_SET_RUNE_PAGE_RSP = 373,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_SET_STR_REQ", Value=374)]
      ZONE_CLI_PREF_SET_STR_REQ = 374,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_PREF_SET_STR_RSP", Value=375)]
      ZONE_CLI_PREF_SET_STR_RSP = 375,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TASK_MARK_REQ", Value=376)]
      ZONE_TASK_MARK_REQ = 376,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_TASK_MARK_RSP", Value=377)]
      ZONE_TASK_MARK_RSP = 377,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_BAG_REQ", Value=378)]
      ZONE_GET_PLAYER_BAG_REQ = 378,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_BAG_RSP", Value=379)]
      ZONE_GET_PLAYER_BAG_RSP = 379,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MODIFY_PLAYER_BAG_REQ", Value=380)]
      ZONE_MODIFY_PLAYER_BAG_REQ = 380,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MODIFY_PLAYER_BAG_RSP", Value=381)]
      ZONE_MODIFY_PLAYER_BAG_RSP = 381,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_LIST_REQ", Value=382)]
      ZONE_GET_PLAYER_LIST_REQ = 382,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_LIST_RSP", Value=383)]
      ZONE_GET_PLAYER_LIST_RSP = 383,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CONFIG_LIST_REQ", Value=384)]
      ZONE_CONFIG_LIST_REQ = 384,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CONFIG_LIST_RSP", Value=385)]
      ZONE_CONFIG_LIST_RSP = 385,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_ADD_REQ", Value=386)]
      ZONE_FRIEND_REQ_ADD_REQ = 386,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_ADD_RSP", Value=387)]
      ZONE_FRIEND_REQ_ADD_RSP = 387,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_LIST_REQ", Value=388)]
      ZONE_FRIEND_REQ_LIST_REQ = 388,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_LIST_RSP", Value=389)]
      ZONE_FRIEND_REQ_LIST_RSP = 389,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_DEL_REQ", Value=390)]
      ZONE_FRIEND_REQ_DEL_REQ = 390,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_DEL_RSP", Value=391)]
      ZONE_FRIEND_REQ_DEL_RSP = 391,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_CONFIRM_REQ", Value=392)]
      ZONE_FRIEND_REQ_CONFIRM_REQ = 392,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_CONFIRM_RSP", Value=393)]
      ZONE_FRIEND_REQ_CONFIRM_RSP = 393,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEARCH_PLAYER_BY_UIN_REQ", Value=394)]
      ZONE_SEARCH_PLAYER_BY_UIN_REQ = 394,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEARCH_PLAYER_BY_UIN_RSP", Value=395)]
      ZONE_SEARCH_PLAYER_BY_UIN_RSP = 395,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_INNER_FRIEND_DEL_REQ", Value=396)]
      ZONE_INNER_FRIEND_DEL_REQ = 396,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_INNER_FRIEND_DEL_RSP", Value=397)]
      ZONE_INNER_FRIEND_DEL_RSP = 397,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_ADD_BAN_REQ", Value=398)]
      ZONE_FRIEND_REQ_ADD_BAN_REQ = 398,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_REQ_ADD_BAN_RSP", Value=399)]
      ZONE_FRIEND_REQ_ADD_BAN_RSP = 399,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_INNER_FRIEND_LIST_REQ", Value=400)]
      ZONE_GET_INNER_FRIEND_LIST_REQ = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_INNER_FRIEND_LIST_RSP", Value=401)]
      ZONE_GET_INNER_FRIEND_LIST_RSP = 401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEND_FRIEND_COIN_REQ", Value=402)]
      ZONE_SEND_FRIEND_COIN_REQ = 402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEND_FRIEND_COIN_RSP", Value=403)]
      ZONE_SEND_FRIEND_COIN_RSP = 403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_FRIEND_DATA_CHANGED_NOTIFY", Value=404)]
      ZONE_FRIEND_DATA_CHANGED_NOTIFY = 404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_STAT_REPORT_REQ", Value=410)]
      ZONE_CLI_STAT_REPORT_REQ = 410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CLI_STAT_REPORT_RSP", Value=411)]
      ZONE_CLI_STAT_REPORT_RSP = 411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_STATISTICS_REQ", Value=416)]
      ZONE_GET_PLAYER_STATISTICS_REQ = 416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_STATISTICS_RSP", Value=417)]
      ZONE_GET_PLAYER_STATISTICS_RSP = 417,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ALTER_CLI_SET_REQ", Value=418)]
      ZONE_ALTER_CLI_SET_REQ = 418,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ALTER_CLI_SET_RSP", Value=419)]
      ZONE_ALTER_CLI_SET_RSP = 419,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CHAMPION_LIST_REQ", Value=420)]
      ZONE_CHAMPION_LIST_REQ = 420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CHAMPION_LIST_RSP", Value=421)]
      ZONE_CHAMPION_LIST_RSP = 421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_AI_SETTING_LIST_REQ", Value=422)]
      ZONE_AI_SETTING_LIST_REQ = 422,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_AI_SETTING_LIST_RSP", Value=423)]
      ZONE_AI_SETTING_LIST_RSP = 423,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_AI_SETTING_SET_REQ", Value=424)]
      ZONE_AI_SETTING_SET_REQ = 424,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_AI_SETTING_SET_RSP", Value=425)]
      ZONE_AI_SETTING_SET_RSP = 425,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_SCENE_REQ", Value=426)]
      ZONE_SET_SCENE_REQ = 426,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_SCENE_RSP", Value=427)]
      ZONE_SET_SCENE_RSP = 427,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_PLAYER_ICON_AND_FRAME_REQ", Value=433)]
      ZONE_SET_PLAYER_ICON_AND_FRAME_REQ = 433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_PLAYER_ICON_AND_FRAME_RSP", Value=434)]
      ZONE_SET_PLAYER_ICON_AND_FRAME_RSP = 434,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_ELO_REQ", Value=435)]
      ZONE_SET_ELO_REQ = 435,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_ELO_RSP", Value=436)]
      ZONE_SET_ELO_RSP = 436,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_IS_NEWBIE_REQ", Value=437)]
      ZONE_SET_IS_NEWBIE_REQ = 437,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_IS_NEWBIE_RSP", Value=438)]
      ZONE_SET_IS_NEWBIE_RSP = 438,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GM_PLAYER_CLEAR_REQ", Value=439)]
      ZONE_GM_PLAYER_CLEAR_REQ = 439,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GM_PLAYER_CLEAR_RSP", Value=440)]
      ZONE_GM_PLAYER_CLEAR_RSP = 440,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_RPT_PLAYER_LOCAL_TRAINING_REQ", Value=441)]
      ZONE_RPT_PLAYER_LOCAL_TRAINING_REQ = 441,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_RPT_PLAYER_LOCAL_TRAINING_RSP", Value=442)]
      ZONE_RPT_PLAYER_LOCAL_TRAINING_RSP = 442,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_VOIP_MEMBER_RPT_REQ", Value=443)]
      ZONE_ROOM_VOIP_MEMBER_RPT_REQ = 443,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_VOIP_MEMBER_RPT_RSP", Value=444)]
      ZONE_ROOM_VOIP_MEMBER_RPT_RSP = 444,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_EVENT_REPORT_REQ", Value=445)]
      ZONE_EVENT_REPORT_REQ = 445,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_EVENT_REPORT_RSP", Value=446)]
      ZONE_EVENT_REPORT_RSP = 446,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_USER_GUIDE_RPT_REQ", Value=447)]
      ZONE_USER_GUIDE_RPT_REQ = 447,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_USER_GUIDE_RPT_RSP", Value=448)]
      ZONE_USER_GUIDE_RPT_RSP = 448,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_IDIP_EVENT_REQ", Value=449)]
      ZONE_IDIP_EVENT_REQ = 449,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_IDIP_EVENT_RSP", Value=450)]
      ZONE_IDIP_EVENT_RSP = 450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_IDIP_BAN_PLAYER_REQ", Value=451)]
      ZONE_IDIP_BAN_PLAYER_REQ = 451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_IDIP_BAN_PLAYER_RSP", Value=452)]
      ZONE_IDIP_BAN_PLAYER_RSP = 452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_QUERY_PLAYER_STATE_REQ", Value=453)]
      ZONE_QUERY_PLAYER_STATE_REQ = 453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_QUERY_PLAYER_STATE_RSP", Value=454)]
      ZONE_QUERY_PLAYER_STATE_RSP = 454,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_KICK_OFF_NOTIFY", Value=498)]
      ZONE_KICK_OFF_NOTIFY = 498,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_PLAYER_EXIT_NOTIFY", Value=499)]
      ZONE_ROOM_PLAYER_EXIT_NOTIFY = 499,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MARQUEE_BROADCAST_NOTIFY", Value=500)]
      ZONE_MARQUEE_BROADCAST_NOTIFY = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_VOIP_MEMBER_NOTIFY", Value=501)]
      ZONE_ROOM_VOIP_MEMBER_NOTIFY = 501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MATCH_FAIL_NOTIFY", Value=502)]
      ZONE_MATCH_FAIL_NOTIFY = 502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_PLAYER_MSG_NOTIFY", Value=503)]
      ZONE_PLAYER_MSG_NOTIFY = 503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_PLAYER_STATE_NOTIFY", Value=504)]
      ZONE_PLAYER_STATE_NOTIFY = 504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_PLAYER_INFO_NOTIFY", Value=505)]
      ZONE_PLAYER_INFO_NOTIFY = 505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_CANCLE_MATCH_NOTIFY", Value=506)]
      ZONE_CANCLE_MATCH_NOTIFY = 506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_START_MATCH_NOTIFY", Value=507)]
      ZONE_ROOM_START_MATCH_NOTIFY = 507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_DEL_PALYER_NOTIFY", Value=508)]
      ZONE_ROOM_DEL_PALYER_NOTIFY = 508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_CHAT_NOTIFY", Value=509)]
      ZONE_ROOM_CHAT_NOTIFY = 509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_INVITE_NOTIFY", Value=510)]
      ZONE_ROOM_INVITE_NOTIFY = 510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ROOM_NOTIFY", Value=511)]
      ZONE_ROOM_NOTIFY = 511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_PLAYER_SYNC_NOTIFY", Value=512)]
      ZONE_PLAYER_SYNC_NOTIFY = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_BROADCAST_NOTIFY_TEST", Value=768)]
      ZONE_BROADCAST_NOTIFY_TEST = 768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEND_FRIEND_MSG_REQ", Value=513)]
      ZONE_SEND_FRIEND_MSG_REQ = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEND_FRIEND_MSG_RSP", Value=514)]
      ZONE_SEND_FRIEND_MSG_RSP = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEND_WORLD_MSG_REQ", Value=515)]
      ZONE_SEND_WORLD_MSG_REQ = 515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SEND_WORLD_MSG_RSP", Value=516)]
      ZONE_SEND_WORLD_MSG_RSP = 516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_MSG_NOTIFY", Value=517)]
      ZONE_MSG_NOTIFY = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_MSG_MASK_REQ", Value=519)]
      ZONE_SET_MSG_MASK_REQ = 519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_SET_MSG_MASK_RSP", Value=520)]
      ZONE_SET_MSG_MASK_RSP = 520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_MSG_MASK_REQ", Value=521)]
      ZONE_GET_MSG_MASK_REQ = 521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_MSG_MASK_RSP", Value=522)]
      ZONE_GET_MSG_MASK_RSP = 522,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_UNSET_MSG_MASK_REQ", Value=523)]
      ZONE_UNSET_MSG_MASK_REQ = 523,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_UNSET_MSG_MASK_RSP", Value=524)]
      ZONE_UNSET_MSG_MASK_RSP = 524,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_SIMPLE_INFO_REQ", Value=525)]
      ZONE_GET_PLAYER_SIMPLE_INFO_REQ = 525,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_SIMPLE_INFO_RSP", Value=526)]
      ZONE_GET_PLAYER_SIMPLE_INFO_RSP = 526,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_CHAT_REQ", Value=527)]
      ZONE_LIVE_CHAT_REQ = 527,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_CHAT_RSP", Value=528)]
      ZONE_LIVE_CHAT_RSP = 528,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_CHAT_MASK_REQ", Value=529)]
      ZONE_LIVE_CHAT_MASK_REQ = 529,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LIVE_CHAT_MASK_RSP", Value=530)]
      ZONE_LIVE_CHAT_MASK_RSP = 530,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ACHIEVEMENT_CUP_SET_REQ", Value=592)]
      ZONE_ACHIEVEMENT_CUP_SET_REQ = 592,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_ACHIEVEMENT_CUP_SET_RSP", Value=593)]
      ZONE_ACHIEVEMENT_CUP_SET_RSP = 593,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LOGOUT_REQ", Value=594)]
      ZONE_LOGOUT_REQ = 594,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_LOGOUT_RSP", Value=595)]
      ZONE_LOGOUT_RSP = 595,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_BALANCE_REQ", Value=596)]
      ZONE_GET_PLAYER_BALANCE_REQ = 596,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZONE_GET_PLAYER_BALANCE_RSP", Value=597)]
      ZONE_GET_PLAYER_BALANCE_RSP = 597
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameSvrCmd")]
    public enum GameSvrCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MESSAGE_TYPE_GAME", Value=3)]
      MESSAGE_TYPE_GAME = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_HEART_BEAT", Value=768)]
      GAME_HEART_BEAT = 768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_JOIN_REQ", Value=769)]
      GAME_JOIN_REQ = 769,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_JOIN_RSP", Value=770)]
      GAME_JOIN_RSP = 770,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_LOADRES_RPT_REPORT", Value=771)]
      GAME_LOADRES_RPT_REPORT = 771,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_LOADRES_RPT_NOTIFY", Value=772)]
      GAME_LOADRES_RPT_NOTIFY = 772,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_START_NOTIFY", Value=773)]
      GAME_START_NOTIFY = 773,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_LOGIC_ACTION_SEND", Value=774)]
      GAME_LOGIC_ACTION_SEND = 774,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_LOGIC_FRAME_SYNC", Value=775)]
      GAME_LOGIC_FRAME_SYNC = 775,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_LOGIC_END_REPORT", Value=776)]
      GAME_LOGIC_END_REPORT = 776,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_LOGIC_END_NOTIFY", Value=777)]
      GAME_LOGIC_END_NOTIFY = 777,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_PING_REQ", Value=784)]
      GAME_PING_REQ = 784,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_PING_RSP", Value=785)]
      GAME_PING_RSP = 785,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RPT_HASHCODE_REQ", Value=786)]
      GAME_RPT_HASHCODE_REQ = 786,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RPT_HASHCODE_RSP", Value=787)]
      GAME_RPT_HASHCODE_RSP = 787,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_GET_LOST_FRAME_REQ", Value=790)]
      GAME_GET_LOST_FRAME_REQ = 790,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_EXIT_REQ", Value=791)]
      GAME_EXIT_REQ = 791,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_EXIT_RSP", Value=792)]
      GAME_EXIT_RSP = 792,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_READY_REQ", Value=803)]
      GAME_READY_REQ = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_READY_RSP", Value=804)]
      GAME_READY_RSP = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RECONNECT_REQ", Value=805)]
      GAME_RECONNECT_REQ = 805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RECONNECT_RSP", Value=806)]
      GAME_RECONNECT_RSP = 806
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DirSvrCmd")]
    public enum DirSvrCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_GET_INFO_REQ", Value=2049)]
      DIR_GET_INFO_REQ = 2049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_GET_INFO_RSP", Value=2050)]
      DIR_GET_INFO_RSP = 2050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_GET_LIST_REQ", Value=2051)]
      DIR_GET_LIST_REQ = 2051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_GET_LIST_RSP", Value=2052)]
      DIR_GET_LIST_RSP = 2052
    }
  
}