//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: dirsvr.proto
// Note: requires additional types generated from: common_data.proto
// Note: requires additional types generated from: dir_data.proto
namespace moba_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirGetInfoReq")]
  public partial class DirGetInfoReq : global::ProtoBuf.IExtensible
  {
    public DirGetInfoReq() {}
    
    private byte[] _openid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"openid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] openid
    {
      get { return _openid?? null; }
      set { _openid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool openidSpecified
    {
      get { return this._openid != null; }
      set { if (value == (this._openid== null)) this._openid = value ? this.openid : (byte[])null; }
    }
    private bool ShouldSerializeopenid() { return openidSpecified; }
    private void Resetopenid() { openidSpecified = false; }
    
    private moba_protocol.PlatType? _plat_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public moba_protocol.PlatType plat_type
    {
      get { return _plat_type?? moba_protocol.PlatType.PLAT_TYPE_ALL; }
      set { _plat_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool plat_typeSpecified
    {
      get { return this._plat_type != null; }
      set { if (value == (this._plat_type== null)) this._plat_type = value ? this.plat_type : (moba_protocol.PlatType?)null; }
    }
    private bool ShouldSerializeplat_type() { return plat_typeSpecified; }
    private void Resetplat_type() { plat_typeSpecified = false; }
    
    private uint? _client_version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint client_version
    {
      get { return _client_version?? default(uint); }
      set { _client_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool client_versionSpecified
    {
      get { return this._client_version != null; }
      set { if (value == (this._client_version== null)) this._client_version = value ? this.client_version : (uint?)null; }
    }
    private bool ShouldSerializeclient_version() { return client_versionSpecified; }
    private void Resetclient_version() { client_versionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirGetInfoRsp")]
  public partial class DirGetInfoRsp : global::ProtoBuf.IExtensible
  {
    public DirGetInfoRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private uint? _total_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_num
    {
      get { return _total_num?? default(uint); }
      set { _total_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool total_numSpecified
    {
      get { return this._total_num != null; }
      set { if (value == (this._total_num== null)) this._total_num = value ? this.total_num : (uint?)null; }
    }
    private bool ShouldSerializetotal_num() { return total_numSpecified; }
    private void Resettotal_num() { total_numSpecified = false; }
    
    private moba_protocol.DirZoneInfo _zone_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"zone_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.DirZoneInfo zone_info
    {
      get { return _zone_info; }
      set { _zone_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.DirZoneInfo> _zone_reg_info = new global::System.Collections.Generic.List<moba_protocol.DirZoneInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"zone_reg_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.DirZoneInfo> zone_reg_info
    {
      get { return _zone_reg_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirGetListReq")]
  public partial class DirGetListReq : global::ProtoBuf.IExtensible
  {
    public DirGetListReq() {}
    
    private byte[] _openid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"openid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] openid
    {
      get { return _openid; }
      set { _openid = value; }
    }
    private moba_protocol.PlatType? _plat_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public moba_protocol.PlatType plat_type
    {
      get { return _plat_type?? moba_protocol.PlatType.PLAT_TYPE_ALL; }
      set { _plat_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool plat_typeSpecified
    {
      get { return this._plat_type != null; }
      set { if (value == (this._plat_type== null)) this._plat_type = value ? this.plat_type : (moba_protocol.PlatType?)null; }
    }
    private bool ShouldSerializeplat_type() { return plat_typeSpecified; }
    private void Resetplat_type() { plat_typeSpecified = false; }
    
    private uint? _client_version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint client_version
    {
      get { return _client_version?? default(uint); }
      set { _client_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool client_versionSpecified
    {
      get { return this._client_version != null; }
      set { if (value == (this._client_version== null)) this._client_version = value ? this.client_version : (uint?)null; }
    }
    private bool ShouldSerializeclient_version() { return client_versionSpecified; }
    private void Resetclient_version() { client_versionSpecified = false; }
    
    private uint? _list_begin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"list_begin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint list_begin
    {
      get { return _list_begin?? default(uint); }
      set { _list_begin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool list_beginSpecified
    {
      get { return this._list_begin != null; }
      set { if (value == (this._list_begin== null)) this._list_begin = value ? this.list_begin : (uint?)null; }
    }
    private bool ShouldSerializelist_begin() { return list_beginSpecified; }
    private void Resetlist_begin() { list_beginSpecified = false; }
    
    private uint? _zone_num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"zone_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zone_num
    {
      get { return _zone_num?? default(uint); }
      set { _zone_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool zone_numSpecified
    {
      get { return this._zone_num != null; }
      set { if (value == (this._zone_num== null)) this._zone_num = value ? this.zone_num : (uint?)null; }
    }
    private bool ShouldSerializezone_num() { return zone_numSpecified; }
    private void Resetzone_num() { zone_numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirGetListRsp")]
  public partial class DirGetListRsp : global::ProtoBuf.IExtensible
  {
    public DirGetListRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private uint? _list_begin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"list_begin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint list_begin
    {
      get { return _list_begin?? default(uint); }
      set { _list_begin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool list_beginSpecified
    {
      get { return this._list_begin != null; }
      set { if (value == (this._list_begin== null)) this._list_begin = value ? this.list_begin : (uint?)null; }
    }
    private bool ShouldSerializelist_begin() { return list_beginSpecified; }
    private void Resetlist_begin() { list_beginSpecified = false; }
    
    private uint? _zone_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"zone_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zone_num
    {
      get { return _zone_num?? default(uint); }
      set { _zone_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool zone_numSpecified
    {
      get { return this._zone_num != null; }
      set { if (value == (this._zone_num== null)) this._zone_num = value ? this.zone_num : (uint?)null; }
    }
    private bool ShouldSerializezone_num() { return zone_numSpecified; }
    private void Resetzone_num() { zone_numSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<moba_protocol.DirZoneInfo> _zone_list = new global::System.Collections.Generic.List<moba_protocol.DirZoneInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"zone_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.DirZoneInfo> zone_list
    {
      get { return _zone_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}