//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: errorcode.proto
namespace moba_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MOBA_RET")]
  public partial class MOBA_RET : global::ProtoBuf.IExtensible
  {
    public MOBA_RET() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=-1)]
      FAIL = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_BEGIN", Value=1000)]
      ERR_COMMON_BEGIN = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_ENCODE_FAILED", Value=1001)]
      ERR_COMMON_ENCODE_FAILED = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_DECODE_FAILED", Value=1002)]
      ERR_COMMON_DECODE_FAILED = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_INVALID_REQUEST", Value=1003)]
      ERR_COMMON_INVALID_REQUEST = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_PB_PARSE_FAIL", Value=1004)]
      ERR_COMMON_PB_PARSE_FAIL = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_SENDMSG_FAIL", Value=1005)]
      ERR_COMMON_SENDMSG_FAIL = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_TIME_OUT", Value=1006)]
      ERR_COMMON_TIME_OUT = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_VERSION_ERROR", Value=1007)]
      ERR_COMMON_VERSION_ERROR = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_MAX_REG_LIMIT", Value=1008)]
      ERR_COMMON_MAX_REG_LIMIT = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_BAN", Value=1009)]
      ERR_COMMON_BAN = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_ACCESS_DENIED", Value=1010)]
      ERR_COMMON_ACCESS_DENIED = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_WORLD_UNMATCH", Value=1011)]
      ERR_COMMON_WORLD_UNMATCH = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_CKV_ERROR", Value=1012)]
      ERR_COMMON_CKV_ERROR = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_DATA_VERSION_ERR", Value=1013)]
      ERR_COMMON_DATA_VERSION_ERR = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_INVALID_WORLID", Value=1014)]
      ERR_COMMON_INVALID_WORLID = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_KICK_FAIL", Value=1015)]
      ERR_COMMON_KICK_FAIL = 1015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_LOGIN_FORBID", Value=1016)]
      ERR_COMMON_LOGIN_FORBID = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_SAVE_FROM_ERR_ZONE", Value=1017)]
      ERR_COMMON_SAVE_FROM_ERR_ZONE = 1017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_INVALID_CONFIG", Value=1018)]
      ERR_COMMON_INVALID_CONFIG = 1018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_UNKNOW_GOODS_TYPE", Value=1019)]
      ERR_COMMON_UNKNOW_GOODS_TYPE = 1019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_CHANNEL_NOT_MATCH", Value=1020)]
      ERR_COMMON_CHANNEL_NOT_MATCH = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_PCL_AUTH_FAILED", Value=1021)]
      ERR_COMMON_PCL_AUTH_FAILED = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_DISCARD_RETURN", Value=1022)]
      ERR_COMMON_DISCARD_RETURN = 1022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_TCAPLUS_ERROR", Value=1023)]
      ERR_COMMON_TCAPLUS_ERROR = 1023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_NULL_PLAYER", Value=1024)]
      ERR_COMMON_NULL_PLAYER = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_BAG_INVALID_ITEM", Value=1025)]
      ERR_COMMON_BAG_INVALID_ITEM = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_BAG_NO_USE", Value=1026)]
      ERR_COMMON_BAG_NO_USE = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_BAG_NO_SELL", Value=1027)]
      ERR_COMMON_BAG_NO_SELL = 1027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_BAG_NOT_ENOUGH", Value=1028)]
      ERR_COMMON_BAG_NOT_ENOUGH = 1028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_NULL_PACKET", Value=1029)]
      ERR_COMMON_NULL_PACKET = 1029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_CONFIG_NOT_FOND", Value=1030)]
      ERR_COMMON_CONFIG_NOT_FOND = 1030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_STATUS_NOT_MATCH", Value=1031)]
      ERR_COMMON_STATUS_NOT_MATCH = 1031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_LOGIN_PROCESSING", Value=1032)]
      ERR_COMMON_LOGIN_PROCESSING = 1032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_LOGIN_REPLACE", Value=1033)]
      ERR_COMMON_LOGIN_REPLACE = 1033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_LOGIN_DISALLOW", Value=1034)]
      ERR_COMMON_LOGIN_DISALLOW = 1034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_VERSION_NOT_SAME", Value=1035)]
      ERR_COMMON_VERSION_NOT_SAME = 1035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_COMMON_VERSION_IS_OLD", Value=1036)]
      ERR_COMMON_VERSION_IS_OLD = 1036
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ZoneErr")]
    public enum ZoneErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_NEED_REGIST", Value=2000)]
      ERR_ZONE_NEED_REGIST = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_ALREADY_REGIST", Value=2001)]
      ERR_ZONE_ALREADY_REGIST = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_ALLOC_PLAYER_FAILED", Value=2002)]
      ERR_ZONE_ALLOC_PLAYER_FAILED = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_GAME_JOIN_FAIL", Value=2003)]
      ERR_ZONE_GAME_JOIN_FAIL = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_NEED_LOGIN", Value=2004)]
      ERR_ZONE_NEED_LOGIN = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_PLAYER_IS_NOT_IDLE", Value=2005)]
      ERR_ZONE_PLAYER_IS_NOT_IDLE = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_PLAYER_IS_IDLE", Value=2006)]
      ERR_ZONE_PLAYER_IS_IDLE = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_INVALID_GAMEID", Value=2007)]
      ERR_ZONE_INVALID_GAMEID = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_INVALID_OPENID", Value=2008)]
      ERR_ZONE_INVALID_OPENID = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_VERSION_NOT_SAME", Value=2009)]
      ERR_ZONE_VERSION_NOT_SAME = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_SUMMONER_ID_NULL", Value=2010)]
      ERR_ZONE_SUMMONER_ID_NULL = 2010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_SUMMONER_ID_IS_NOT_ENOUGH", Value=2011)]
      ERR_ZONE_SUMMONER_ID_IS_NOT_ENOUGH = 2011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MAIL_ID_IS_EMPTY", Value=2012)]
      ERR_ZONE_MAIL_ID_IS_EMPTY = 2012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_TASK_NOT_REWARD", Value=2013)]
      ERR_ZONE_TASK_NOT_REWARD = 2013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_TASK_ADD_REWARD_FAILED", Value=2014)]
      ERR_ZONE_TASK_ADD_REWARD_FAILED = 2014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_PLAYER_INFO_NULL", Value=2015)]
      ERR_ZONE_PLAYER_INFO_NULL = 2015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MALL_INVALID_ITEM", Value=2016)]
      ERR_ZONE_MALL_INVALID_ITEM = 2016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MALL_DISABLED", Value=2017)]
      ERR_ZONE_MALL_DISABLED = 2017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MALL_INVALID_PRICE_IDX", Value=2018)]
      ERR_ZONE_MALL_INVALID_PRICE_IDX = 2018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MALL_COST_GOODS_NOT_ENOUGH", Value=2019)]
      ERR_ZONE_MALL_COST_GOODS_NOT_ENOUGH = 2019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MALL_ADD_GOODS_FAILED", Value=2020)]
      ERR_ZONE_MALL_ADD_GOODS_FAILED = 2020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_MALL_NOT_IN_TIME_RANGE", Value=2021)]
      ERR_ZONE_MALL_NOT_IN_TIME_RANGE = 2021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_RUNE_PAGE_NOT_EXSIT", Value=2022)]
      ERR_ZONE_RUNE_PAGE_NOT_EXSIT = 2022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_RUNE_SLOT_NOT_EXSIT", Value=2023)]
      ERR_ZONE_RUNE_SLOT_NOT_EXSIT = 2023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_HAS_NO_RUNE_SLOT", Value=2024)]
      ERR_ZONE_HAS_NO_RUNE_SLOT = 2024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_HAS_NO_RUNE_PAGE", Value=2025)]
      ERR_ZONE_HAS_NO_RUNE_PAGE = 2025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_HAS_NOT_ENOUGH_DIAMOND", Value=2026)]
      ERR_ZONE_HAS_NOT_ENOUGH_DIAMOND = 2026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_HAS_NOT_ENOUGH_COIN", Value=2027)]
      ERR_ZONE_HAS_NOT_ENOUGH_COIN = 2027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_HAS_NOT_ENOUGH_COUPON", Value=2028)]
      ERR_ZONE_HAS_NOT_ENOUGH_COUPON = 2028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_RUNE_NOT_ENOUGH", Value=2029)]
      ERR_ZONE_RUNE_NOT_ENOUGH = 2029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_RUNE_SLOT_NOT_UNLOCK", Value=2030)]
      ERR_ZONE_RUNE_SLOT_NOT_UNLOCK = 2030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_RUNE_SLOT_NOT_MATCH", Value=2031)]
      ERR_ZONE_RUNE_SLOT_NOT_MATCH = 2031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_INVALID_RUNE", Value=2032)]
      ERR_ZONE_INVALID_RUNE = 2032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_INVALID_MAIL", Value=2033)]
      ERR_ZONE_INVALID_MAIL = 2033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_CHAMPION_IS_EXIsT", Value=2034)]
      ERR_ZONE_CHAMPION_IS_EXIsT = 2034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_AVATAR_IS_EXIsT", Value=2035)]
      ERR_ZONE_AVATAR_IS_EXIsT = 2035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_CHAMPION_BITS_NOT_FOUND", Value=2036)]
      ERR_ZONE_CHAMPION_BITS_NOT_FOUND = 2036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_AVATAR_BITS_NOT_FOUND", Value=2037)]
      ERR_ZONE_AVATAR_BITS_NOT_FOUND = 2037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_BUFF_OUT_OF_LEN", Value=2038)]
      ERR_ZONE_BUFF_OUT_OF_LEN = 2038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_SETTLE_GOODS_FAIL", Value=2039)]
      ERR_ZONE_SETTLE_GOODS_FAIL = 2039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_SETTLE_REWARD_FAIL", Value=2040)]
      ERR_ZONE_SETTLE_REWARD_FAIL = 2040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_COIN_SEND_LIMIT", Value=2041)]
      ERR_ZONE_COIN_SEND_LIMIT = 2041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_CHECK_FRIEND_NOT_FRIEND", Value=2042)]
      ERR_ZONE_CHECK_FRIEND_NOT_FRIEND = 2042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_CHECK_FRIEND_MASK_MSG_MASKED", Value=2043)]
      ERR_ZONE_CHECK_FRIEND_MASK_MSG_MASKED = 2043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_DUPLICATE_NAME", Value=2044)]
      ERR_ZONE_DUPLICATE_NAME = 2044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_NAME_LEN_TOOLONG", Value=2045)]
      ERR_ZONE_NAME_LEN_TOOLONG = 2045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_ILLEGAL_NAME", Value=2046)]
      ERR_ZONE_ILLEGAL_NAME = 2046
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameErr")]
    public enum GameErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_ROLE_NOT_EXSIT", Value=3001)]
      ERR_GAME_ROLE_NOT_EXSIT = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_NOT_EXSIT", Value=3002)]
      ERR_GAME_NOT_EXSIT = 3002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_ROLE_IS_NOT_LOSE", Value=3003)]
      ERR_GAME_ROLE_IS_NOT_LOSE = 3003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_LOADRESRPT_IN_ERROR_STATE", Value=3004)]
      ERR_GAME_LOADRESRPT_IN_ERROR_STATE = 3004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_PARAM_NOT_MATCH", Value=3005)]
      ERR_GAME_PARAM_NOT_MATCH = 3005
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LobbySvrErr")]
    public enum LobbySvrErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOM_JOIN_FAIL", Value=4001)]
      ERR_LOBBYSVR_ROOM_JOIN_FAIL = 4001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_CHAMPION_IS_SELECT", Value=4002)]
      ERR_LOBBYSVR_CHAMPION_IS_SELECT = 4002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_CHAMPION_IS_CONFIRM", Value=4003)]
      ERR_LOBBYSVR_CHAMPION_IS_CONFIRM = 4003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_CHAMPION_IS_NOT_SELECT", Value=4004)]
      ERR_LOBBYSVR_CHAMPION_IS_NOT_SELECT = 4004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOM_EXIT_FAIL", Value=4005)]
      ERR_LOBBYSVR_ROOM_EXIT_FAIL = 4005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOM_CREATE_FAIL", Value=4006)]
      ERR_LOBBYSVR_ROOM_CREATE_FAIL = 4006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_PLAYER_IS_IN_ROOM", Value=4007)]
      ERR_LOBBYSVR_PLAYER_IS_IN_ROOM = 4007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOM_IS_FULL", Value=4008)]
      ERR_LOBBYSVR_ROOM_IS_FULL = 4008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOM_IS_NOT_EXSIT", Value=4009)]
      ERR_LOBBYSVR_ROOM_IS_NOT_EXSIT = 4009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_PLAYER_IS_NOT_EXSIT", Value=4010)]
      ERR_LOBBYSVR_PLAYER_IS_NOT_EXSIT = 4010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_CHAMPIONID_IS_NOT_MATCH", Value=4011)]
      ERR_LOBBYSVR_CHAMPIONID_IS_NOT_MATCH = 4011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_PLAYER_IS_NOT_OWNER", Value=4012)]
      ERR_LOBBYSVR_PLAYER_IS_NOT_OWNER = 4012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_GAME_SETTLE_DUPLICATE", Value=4020)]
      ERR_LOBBYSVR_GAME_SETTLE_DUPLICATE = 4020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_GAME_UNMATCHED_GAMEID", Value=4021)]
      ERR_LOBBYSVR_GAME_UNMATCHED_GAMEID = 4021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_SETTLEDATA_PARSE_FAIL", Value=4022)]
      ERR_LOBBYSVR_SETTLEDATA_PARSE_FAIL = 4022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_SETTLEDATA_ILLEGALLY", Value=4023)]
      ERR_LOBBYSVR_SETTLEDATA_ILLEGALLY = 4023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_GAME_SETTLE_WAITING", Value=4024)]
      ERR_LOBBYSVR_GAME_SETTLE_WAITING = 4024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOM_IS_NOT_FULL", Value=4025)]
      ERR_LOBBYSVR_ROOM_IS_NOT_FULL = 4025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOBBYSVR_ROOMOWNER_IS_NOT_MATCH", Value=4026)]
      ERR_LOBBYSVR_ROOMOWNER_IS_NOT_MATCH = 4026
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MatchSvrErr")]
    public enum MatchSvrErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MATCHSVR_ADD_ROLE_FAIL", Value=5001)]
      ERR_MATCHSVR_ADD_ROLE_FAIL = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MATCHSVR_DECODE_ERR", Value=5002)]
      ERR_MATCHSVR_DECODE_ERR = 5002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MATCHSVR_ROLE_NOT_FOUND", Value=5003)]
      ERR_MATCHSVR_ROLE_NOT_FOUND = 5003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MATCH_TIMEOUT", Value=5004)]
      ERR_MATCH_TIMEOUT = 5004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MATCH_ROLE_IS_EXSIT", Value=5005)]
      ERR_MATCH_ROLE_IS_EXSIT = 5005
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BroadSvrErr")]
    public enum BroadSvrErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PARSE_BROADCAST_REQ_FAIL", Value=6001)]
      ERR_PARSE_BROADCAST_REQ_FAIL = 6001
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DbErr")]
    public enum DbErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_LOAD_EMPTY", Value=1200)]
      DB_DATA_LOAD_EMPTY = 1200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_LOAD_FAILED", Value=12001)]
      DB_DATA_LOAD_FAILED = 12001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_PARSE_FAILED", Value=12002)]
      DB_DATA_PARSE_FAILED = 12002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_LOADFROMMYSQL", Value=12003)]
      DB_DATA_LOADFROMMYSQL = 12003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_SAVE_UIN_WONG", Value=12004)]
      DB_DATA_SAVE_UIN_WONG = 12004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_SAVE_FAILED", Value=12005)]
      DB_DATA_SAVE_FAILED = 12005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_SAVE_PUT_ERR", Value=12006)]
      DB_DATA_SAVE_PUT_ERR = 12006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_UPDATE_FAILED", Value=12007)]
      DB_DATA_UPDATE_FAILED = 12007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_LOADFROMTCAPLUS", Value=12008)]
      DB_DATA_LOADFROMTCAPLUS = 12008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_INSERT_KEY_EXIST", Value=12009)]
      DB_DATA_INSERT_KEY_EXIST = 12009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_DATA_REQ_INVALID", Value=12010)]
      DB_DATA_REQ_INVALID = 12010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_MAIL_ID_NOT_EXSIT", Value=12011)]
      DB_MAIL_ID_NOT_EXSIT = 12011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_MAIL_IS_RECV", Value=12012)]
      DB_MAIL_IS_RECV = 12012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_MAIL_NO_ATTACHMENTS", Value=12013)]
      DB_MAIL_NO_ATTACHMENTS = 12013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_MAIL_DEL_HAS_ATTACHMENTS", Value=12014)]
      DB_MAIL_DEL_HAS_ATTACHMENTS = 12014
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailErr")]
    public enum MailErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_COIN_RECV_LIMIT", Value=18001)]
      ERR_MAIL_COIN_RECV_LIMIT = 18001
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FriendError")]
    public enum FriendError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_REQUEST_NOT_EXIST", Value=13000)]
      ERR_FRIEND_REQUEST_NOT_EXIST = 13000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_REQUEST_EXIST", Value=13001)]
      ERR_FRIEND_REQUEST_EXIST = 13001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_REQUEST_FULL", Value=13002)]
      ERR_FRIEND_REQUEST_FULL = 13002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_NOT_EXIST", Value=13003)]
      ERR_FRIEND_NOT_EXIST = 13003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_EXIST", Value=13004)]
      ERR_FRIEND_EXIST = 13004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_FULL", Value=13005)]
      ERR_FRIEND_FULL = 13005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_GIFT_LIMIT", Value=13006)]
      ERR_FRIEND_GIFT_LIMIT = 13006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_GIFT_ALREADY_PRESENT", Value=13007)]
      ERR_FRIEND_GIFT_ALREADY_PRESENT = 13007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FRIEND_GIFT_GET_LIMIT", Value=13008)]
      ERR_FRIEND_GIFT_GET_LIMIT = 13008
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LiveSvrErr")]
    public enum LiveSvrErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LIVE_ROLE_IN_WATCH", Value=15001)]
      ERR_LIVE_ROLE_IN_WATCH = 15001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LIVE_IS_END", Value=15002)]
      ERR_LIVE_IS_END = 15002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TVSvrErr")]
    public enum TVSvrErr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_TV_NOT_EXIST", Value=21001)]
      ERR_TV_NOT_EXIST = 21001
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}