//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: zone_gm.proto
// Note: requires additional types generated from: common_data.proto
// Note: requires additional types generated from: game_data.proto
// Note: requires additional types generated from: xls_enum.proto
namespace moba_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGetPlayerListReq")]
  public partial class ZoneGetPlayerListReq : global::ProtoBuf.IExtensible
  {
    public ZoneGetPlayerListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGetPlayerListRsp")]
  public partial class ZoneGetPlayerListRsp : global::ProtoBuf.IExtensible
  {
    public ZoneGetPlayerListRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.PlayerBriefInfo> _player_list = new global::System.Collections.Generic.List<moba_protocol.PlayerBriefInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"player_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.PlayerBriefInfo> player_list
    {
      get { return _player_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGetPlayerBagReq")]
  public partial class ZoneGetPlayerBagReq : global::ProtoBuf.IExtensible
  {
    public ZoneGetPlayerBagReq() {}
    
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGetPlayerBagRsp")]
  public partial class ZoneGetPlayerBagRsp : global::ProtoBuf.IExtensible
  {
    public ZoneGetPlayerBagRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private moba_protocol.PlayerBagInfo _bag_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bag_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerBagInfo bag_info
    {
      get { return _bag_info; }
      set { _bag_info = value; }
    }
    private moba_protocol.PlayerCommonInfo _common_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"common_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerCommonInfo common_info
    {
      get { return _common_info; }
      set { _common_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.ItemInfo> _champion_list = new global::System.Collections.Generic.List<moba_protocol.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"champion_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ItemInfo> champion_list
    {
      get { return _champion_list; }
    }
  
    private readonly global::System.Collections.Generic.List<moba_protocol.ItemInfo> _avatar_list = new global::System.Collections.Generic.List<moba_protocol.ItemInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"avatar_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ItemInfo> avatar_list
    {
      get { return _avatar_list; }
    }
  
    private moba_protocol.PlayerVItemInfo _vitem_info = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vitem_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerVItemInfo vitem_info
    {
      get { return _vitem_info; }
      set { _vitem_info = value; }
    }
    private moba_protocol.PlayerCliBuffInfo _cli_info = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cli_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerCliBuffInfo cli_info
    {
      get { return _cli_info; }
      set { _cli_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneModifyPlayerBagReq")]
  public partial class ZoneModifyPlayerBagReq : global::ProtoBuf.IExtensible
  {
    public ZoneModifyPlayerBagReq() {}
    
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private moba_protocol.GoodsChangeItem _change = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"change", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.GoodsChangeItem change
    {
      get { return _change; }
      set { _change = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _id_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"id_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> id_list
    {
      get { return _id_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfo")]
  public partial class ItemInfo : global::ProtoBuf.IExtensible
  {
    public ItemInfo() {}
    
    private uint? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id?? default(uint); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (uint?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneModifyPlayerBagRsp")]
  public partial class ZoneModifyPlayerBagRsp : global::ProtoBuf.IExtensible
  {
    public ZoneModifyPlayerBagRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private moba_protocol.PlayerBagInfo _bag_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bag_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerBagInfo bag_info
    {
      get { return _bag_info; }
      set { _bag_info = value; }
    }
    private moba_protocol.PlayerCommonInfo _common_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"common_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerCommonInfo common_info
    {
      get { return _common_info; }
      set { _common_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.ItemInfo> _champion_list = new global::System.Collections.Generic.List<moba_protocol.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"champion_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ItemInfo> champion_list
    {
      get { return _champion_list; }
    }
  
    private readonly global::System.Collections.Generic.List<moba_protocol.ItemInfo> _avatar_list = new global::System.Collections.Generic.List<moba_protocol.ItemInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"avatar_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ItemInfo> avatar_list
    {
      get { return _avatar_list; }
    }
  
    private moba_protocol.PlayerVItemInfo _vitem_info = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vitem_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerVItemInfo vitem_info
    {
      get { return _vitem_info; }
      set { _vitem_info = value; }
    }
    private moba_protocol.PlayerCliBuffInfo _cli_info = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cli_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerCliBuffInfo cli_info
    {
      get { return _cli_info; }
      set { _cli_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfigItem")]
  public partial class ConfigItem : global::ProtoBuf.IExtensible
  {
    public ConfigItem() {}
    
    private uint? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id?? default(uint); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (uint?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private string _desc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc?? ""; }
      set { _desc = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool descSpecified
    {
      get { return this._desc != null; }
      set { if (value == (this._desc== null)) this._desc = value ? this.desc : (string)null; }
    }
    private bool ShouldSerializedesc() { return descSpecified; }
    private void Resetdesc() { descSpecified = false; }
    
    private uint? _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type?? default(uint); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (uint?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneConfigListReq")]
  public partial class ZoneConfigListReq : global::ProtoBuf.IExtensible
  {
    public ZoneConfigListReq() {}
    
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private dataconfig.GoodsType? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public dataconfig.GoodsType type
    {
      get { return _type?? dataconfig.GoodsType.GT_NONE; }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (dataconfig.GoodsType?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneConfigListRsp")]
  public partial class ZoneConfigListRsp : global::ProtoBuf.IExtensible
  {
    public ZoneConfigListRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.ConfigItem> _conf_list = new global::System.Collections.Generic.List<moba_protocol.ConfigItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"conf_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ConfigItem> conf_list
    {
      get { return _conf_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAlterCliSetReq")]
  public partial class ZoneAlterCliSetReq : global::ProtoBuf.IExtensible
  {
    public ZoneAlterCliSetReq() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _int_value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int int_value
    {
      get { return _int_value; }
      set { _int_value = value; }
    }
    private string _str_value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"str_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_value
    {
      get { return _str_value; }
      set { _str_value = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _int_list_value = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"int_list_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> int_list_value
    {
      get { return _int_list_value; }
    }
  
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAlterCliSetRsp")]
  public partial class ZoneAlterCliSetRsp : global::ProtoBuf.IExtensible
  {
    public ZoneAlterCliSetRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private moba_protocol.PlayerBagInfo _bag_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bag_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerBagInfo bag_info
    {
      get { return _bag_info; }
      set { _bag_info = value; }
    }
    private moba_protocol.PlayerCommonInfo _common_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"common_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerCommonInfo common_info
    {
      get { return _common_info; }
      set { _common_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.ItemInfo> _champion_list = new global::System.Collections.Generic.List<moba_protocol.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"champion_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ItemInfo> champion_list
    {
      get { return _champion_list; }
    }
  
    private readonly global::System.Collections.Generic.List<moba_protocol.ItemInfo> _avatar_list = new global::System.Collections.Generic.List<moba_protocol.ItemInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"avatar_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ItemInfo> avatar_list
    {
      get { return _avatar_list; }
    }
  
    private moba_protocol.PlayerVItemInfo _vitem_info = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vitem_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerVItemInfo vitem_info
    {
      get { return _vitem_info; }
      set { _vitem_info = value; }
    }
    private moba_protocol.PlayerCliBuffInfo _cli_info = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cli_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerCliBuffInfo cli_info
    {
      get { return _cli_info; }
      set { _cli_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneChampionListReq")]
  public partial class ZoneChampionListReq : global::ProtoBuf.IExtensible
  {
    public ZoneChampionListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneChampionListRsp")]
  public partial class ZoneChampionListRsp : global::ProtoBuf.IExtensible
  {
    public ZoneChampionListRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private readonly global::System.Collections.Generic.List<moba_protocol.ConfigItem> _conf_list = new global::System.Collections.Generic.List<moba_protocol.ConfigItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"conf_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<moba_protocol.ConfigItem> conf_list
    {
      get { return _conf_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAiSettingListReq")]
  public partial class ZoneAiSettingListReq : global::ProtoBuf.IExtensible
  {
    public ZoneAiSettingListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAiSettingListRsp")]
  public partial class ZoneAiSettingListRsp : global::ProtoBuf.IExtensible
  {
    public ZoneAiSettingListRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private bool? _enable;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enable
    {
      get { return _enable?? default(bool); }
      set { _enable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool enableSpecified
    {
      get { return this._enable != null; }
      set { if (value == (this._enable== null)) this._enable = value ? this.enable : (bool?)null; }
    }
    private bool ShouldSerializeenable() { return enableSpecified; }
    private void Resetenable() { enableSpecified = false; }
    
    private bool? _level_enable;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level_enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool level_enable
    {
      get { return _level_enable?? default(bool); }
      set { _level_enable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool level_enableSpecified
    {
      get { return this._level_enable != null; }
      set { if (value == (this._level_enable== null)) this._level_enable = value ? this.level_enable : (bool?)null; }
    }
    private bool ShouldSerializelevel_enable() { return level_enableSpecified; }
    private void Resetlevel_enable() { level_enableSpecified = false; }
    
    private bool? _salary_rate_enable;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"salary_rate_enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool salary_rate_enable
    {
      get { return _salary_rate_enable?? default(bool); }
      set { _salary_rate_enable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool salary_rate_enableSpecified
    {
      get { return this._salary_rate_enable != null; }
      set { if (value == (this._salary_rate_enable== null)) this._salary_rate_enable = value ? this.salary_rate_enable : (bool?)null; }
    }
    private bool ShouldSerializesalary_rate_enable() { return salary_rate_enableSpecified; }
    private void Resetsalary_rate_enable() { salary_rate_enableSpecified = false; }
    
    private moba_protocol.AiSettingList _ai_setting_list = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ai_setting_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.AiSettingList ai_setting_list
    {
      get { return _ai_setting_list; }
      set { _ai_setting_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAiSettingSetReq")]
  public partial class ZoneAiSettingSetReq : global::ProtoBuf.IExtensible
  {
    public ZoneAiSettingSetReq() {}
    
    private bool? _enable;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enable
    {
      get { return _enable?? default(bool); }
      set { _enable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool enableSpecified
    {
      get { return this._enable != null; }
      set { if (value == (this._enable== null)) this._enable = value ? this.enable : (bool?)null; }
    }
    private bool ShouldSerializeenable() { return enableSpecified; }
    private void Resetenable() { enableSpecified = false; }
    
    private bool? _level_enable;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level_enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool level_enable
    {
      get { return _level_enable?? default(bool); }
      set { _level_enable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool level_enableSpecified
    {
      get { return this._level_enable != null; }
      set { if (value == (this._level_enable== null)) this._level_enable = value ? this.level_enable : (bool?)null; }
    }
    private bool ShouldSerializelevel_enable() { return level_enableSpecified; }
    private void Resetlevel_enable() { level_enableSpecified = false; }
    
    private bool? _salary_rate_enable;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"salary_rate_enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool salary_rate_enable
    {
      get { return _salary_rate_enable?? default(bool); }
      set { _salary_rate_enable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool salary_rate_enableSpecified
    {
      get { return this._salary_rate_enable != null; }
      set { if (value == (this._salary_rate_enable== null)) this._salary_rate_enable = value ? this.salary_rate_enable : (bool?)null; }
    }
    private bool ShouldSerializesalary_rate_enable() { return salary_rate_enableSpecified; }
    private void Resetsalary_rate_enable() { salary_rate_enableSpecified = false; }
    
    private moba_protocol.AiSettingList _ai_setting_list = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ai_setting_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.AiSettingList ai_setting_list
    {
      get { return _ai_setting_list; }
      set { _ai_setting_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAiSettingSetRsp")]
  public partial class ZoneAiSettingSetRsp : global::ProtoBuf.IExtensible
  {
    public ZoneAiSettingSetRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSetEloReq")]
  public partial class ZoneSetEloReq : global::ProtoBuf.IExtensible
  {
    public ZoneSetEloReq() {}
    
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private uint? _elo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"elo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint elo
    {
      get { return _elo?? default(uint); }
      set { _elo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool eloSpecified
    {
      get { return this._elo != null; }
      set { if (value == (this._elo== null)) this._elo = value ? this.elo : (uint?)null; }
    }
    private bool ShouldSerializeelo() { return eloSpecified; }
    private void Resetelo() { eloSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSetEloRsp")]
  public partial class ZoneSetEloRsp : global::ProtoBuf.IExtensible
  {
    public ZoneSetEloRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSetIsNewbieReq")]
  public partial class ZoneSetIsNewbieReq : global::ProtoBuf.IExtensible
  {
    public ZoneSetIsNewbieReq() {}
    
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private bool? _is_newbie;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_newbie", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_newbie
    {
      get { return _is_newbie?? default(bool); }
      set { _is_newbie = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool is_newbieSpecified
    {
      get { return this._is_newbie != null; }
      set { if (value == (this._is_newbie== null)) this._is_newbie = value ? this.is_newbie : (bool?)null; }
    }
    private bool ShouldSerializeis_newbie() { return is_newbieSpecified; }
    private void Resetis_newbie() { is_newbieSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSetIsNewbieRsp")]
  public partial class ZoneSetIsNewbieRsp : global::ProtoBuf.IExtensible
  {
    public ZoneSetIsNewbieRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGmPlayerClearReq")]
  public partial class ZoneGmPlayerClearReq : global::ProtoBuf.IExtensible
  {
    public ZoneGmPlayerClearReq() {}
    
    private uint? _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uin
    {
      get { return _uin?? default(uint); }
      set { _uin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uinSpecified
    {
      get { return this._uin != null; }
      set { if (value == (this._uin== null)) this._uin = value ? this.uin : (uint?)null; }
    }
    private bool ShouldSerializeuin() { return uinSpecified; }
    private void Resetuin() { uinSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGmPlayerClearRsp")]
  public partial class ZoneGmPlayerClearRsp : global::ProtoBuf.IExtensible
  {
    public ZoneGmPlayerClearRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}