//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: zone_rune.proto
// Note: requires additional types generated from: common_data.proto
// Note: requires additional types generated from: rune_data.proto
namespace moba_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGetRuneReq")]
  public partial class ZoneGetRuneReq : global::ProtoBuf.IExtensible
  {
    public ZoneGetRuneReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneGetRuneRsp")]
  public partial class ZoneGetRuneRsp : global::ProtoBuf.IExtensible
  {
    public ZoneGetRuneRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private moba_protocol.PlayerRuneInfo _rune_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rune_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerRuneInfo rune_info
    {
      get { return _rune_info; }
      set { _rune_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAddRunePageReq")]
  public partial class ZoneAddRunePageReq : global::ProtoBuf.IExtensible
  {
    public ZoneAddRunePageReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneAddRunePageRsp")]
  public partial class ZoneAddRunePageRsp : global::ProtoBuf.IExtensible
  {
    public ZoneAddRunePageRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private moba_protocol.PlayerRuneInfo _rune_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rune_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.PlayerRuneInfo rune_info
    {
      get { return _rune_info; }
      set { _rune_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneUnlockRuneSlotReq")]
  public partial class ZoneUnlockRuneSlotReq : global::ProtoBuf.IExtensible
  {
    public ZoneUnlockRuneSlotReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneUnlockRuneSlotRsp")]
  public partial class ZoneUnlockRuneSlotRsp : global::ProtoBuf.IExtensible
  {
    public ZoneUnlockRuneSlotRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private moba_protocol.RuneSlotList _slot_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"slot_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.RuneSlotList slot_info
    {
      get { return _slot_info; }
      set { _slot_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneUpdateRunePageNameReq")]
  public partial class ZoneUpdateRunePageNameReq : global::ProtoBuf.IExtensible
  {
    public ZoneUpdateRunePageNameReq() {}
    
    private uint? _page_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint page_id
    {
      get { return _page_id?? default(uint); }
      set { _page_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool page_idSpecified
    {
      get { return this._page_id != null; }
      set { if (value == (this._page_id== null)) this._page_id = value ? this.page_id : (uint?)null; }
    }
    private bool ShouldSerializepage_id() { return page_idSpecified; }
    private void Resetpage_id() { page_idSpecified = false; }
    
    private string _page_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"page_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string page_name
    {
      get { return _page_name?? ""; }
      set { _page_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool page_nameSpecified
    {
      get { return this._page_name != null; }
      set { if (value == (this._page_name== null)) this._page_name = value ? this.page_name : (string)null; }
    }
    private bool ShouldSerializepage_name() { return page_nameSpecified; }
    private void Resetpage_name() { page_nameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneUpdateRunePageNameRsp")]
  public partial class ZoneUpdateRunePageNameRsp : global::ProtoBuf.IExtensible
  {
    public ZoneUpdateRunePageNameRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSetRunePageReq")]
  public partial class ZoneSetRunePageReq : global::ProtoBuf.IExtensible
  {
    public ZoneSetRunePageReq() {}
    
    private uint? _page_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint page_id
    {
      get { return _page_id?? default(uint); }
      set { _page_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool page_idSpecified
    {
      get { return this._page_id != null; }
      set { if (value == (this._page_id== null)) this._page_id = value ? this.page_id : (uint?)null; }
    }
    private bool ShouldSerializepage_id() { return page_idSpecified; }
    private void Resetpage_id() { page_idSpecified = false; }
    
    private moba_protocol.RuneInfoList _runes = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"runes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public moba_protocol.RuneInfoList runes
    {
      get { return _runes; }
      set { _runes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSetRunePageRsp")]
  public partial class ZoneSetRunePageRsp : global::ProtoBuf.IExtensible
  {
    public ZoneSetRunePageRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSelectRunePageReq")]
  public partial class ZoneSelectRunePageReq : global::ProtoBuf.IExtensible
  {
    public ZoneSelectRunePageReq() {}
    
    private uint? _rune_page_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rune_page_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rune_page_id
    {
      get { return _rune_page_id?? default(uint); }
      set { _rune_page_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rune_page_idSpecified
    {
      get { return this._rune_page_id != null; }
      set { if (value == (this._rune_page_id== null)) this._rune_page_id = value ? this.rune_page_id : (uint?)null; }
    }
    private bool ShouldSerializerune_page_id() { return rune_page_idSpecified; }
    private void Resetrune_page_id() { rune_page_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneSelectRunePageRsp")]
  public partial class ZoneSelectRunePageRsp : global::ProtoBuf.IExtensible
  {
    public ZoneSelectRunePageRsp() {}
    
    private moba_protocol.RetInfo _ret_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public moba_protocol.RetInfo ret_info
    {
      get { return _ret_info; }
      set { _ret_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}