//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: static_data_account.proto
namespace static_data
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACCOUNT")]
  public partial class ACCOUNT : global::ProtoBuf.IExtensible
  {
    public ACCOUNT() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _en_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"en_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string en_name
    {
      get { return _en_name; }
      set { _en_name = value; }
    }
    private string _phone_number;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"phone_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string phone_number
    {
      get { return _phone_number; }
      set { _phone_number = value; }
    }
    private string _real_name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"real_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string real_name
    {
      get { return _real_name; }
      set { _real_name = value; }
    }
    private string _nick_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private double _money;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double money
    {
      get { return _money; }
      set { _money = value; }
    }
    private double _gold;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACCOUNT_ARRAY")]
  public partial class ACCOUNT_ARRAY : global::ProtoBuf.IExtensible
  {
    public ACCOUNT_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<static_data.ACCOUNT> _items = new global::System.Collections.Generic.List<static_data.ACCOUNT>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<static_data.ACCOUNT> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}