//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: static_data_tweet.proto
namespace static_data
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TWEET")]
  public partial class TWEET : global::ProtoBuf.IExtensible
  {
    public TWEET() {}
    
    private int _tweet_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tweet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tweet_id
    {
      get { return _tweet_id; }
      set { _tweet_id = value; }
    }
    private int _user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _tweet_info;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tweet_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tweet_info
    {
      get { return _tweet_info; }
      set { _tweet_info = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _pic_array = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"pic_array", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> pic_array
    {
      get { return _pic_array; }
    }
  
    private int _is_secret;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"is_secret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_secret
    {
      get { return _is_secret; }
      set { _is_secret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TWEET_ARRAY")]
  public partial class TWEET_ARRAY : global::ProtoBuf.IExtensible
  {
    public TWEET_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<static_data.TWEET> _items = new global::System.Collections.Generic.List<static_data.TWEET>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<static_data.TWEET> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}